services:
  db:
    image: postgres:15-alpine
    container_name: mizdb-postgres
    volumes:
      - "$DATA_DIR:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "$DB_NAME"
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    restart: unless-stopped
    secrets:
      - db_password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
    shm_size: 128mb

  web:
    build: .
    container_name: mizdb-app
    volumes:
      - "$LOG_DIR:/var/log/mizdb"
      - ${PWD}/settings.py:/mizdb/settings.py
    env_file:
      - .env
    ports:
      - 80:8000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    entrypoint: ["/mizdb/docker-entrypoint.sh"]
    command: ["/etc/mizdb-server/apachectl", "start", "-DFOREGROUND"]

secrets:
  db_password:
    file: .passwd
