site_name: MIZDB - Hilfe
theme:
  name: mkdocs
  custom_dir: 'docs_theme/'
  navigation_depth: 3
  locale: de
use_directory_urls: false
hooks:
  - 'docs/hooks/post_build.py'
plugins:
  - search
  - glightbox
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition