site_name: My Docs
theme:
  name: mkdocs
  custom_dir: 'docs_theme/'
hooks:
  - 'docs/hooks/post_build.py'
use_directory_urls: false
plugins:
   - glightbox
markdown_extensions:
  - attr_list
  - md_in_html