site_name: My Docs
theme:
  name: null
  custom_dir: 'docs_theme/'
  static_templates:
    - main.html
hooks:
  - 'docs/hooks/mizdb_hooks.py'
use_directory_urls: false
plugins:
   - glightbox
markdown_extensions:
  - attr_list
  - md_in_html