[mypy]
files = dbentry/
follow_imports = skip
ignore_missing_imports = True
show_error_codes = True
pretty = True
;disallow_untyped_defs = True
plugins = mypy_django_plugin.main

; https://mypy.readthedocs.io/en/stable/config_file.html#confval-exclude
exclude = (?x)(
    migrations/
    |management/
    |dbentry/autocomplete/\w+\.py
    |dbentry/site/
  )

[mypy.plugins.django-stubs]
django_settings_module = "MIZDB.settings"