[project]
name = "MIZDB"
authors = [
    {name = "Philip Becker", email = "yummytea1@gmail.com"},
]
classifiers = [
    "Framework :: Django",
    "Programming Language :: Python :: 3",
]
readme = "README.md"
requires-python = ">=3.9"
dynamic = ["version"]

[tool.uv.pip]
generate-hashes = true
