# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schlagzeile', models.CharField(max_length=100)),
                ('zusammenfassung', models.CharField(blank=True, max_length=100)),
                ('seite', models.IntegerField()),
                ('seitenumfang', models.CharField(blank=True, choices=[('f', 'f'), ('ff', 'ff')], default=None, max_length=3)),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
            },
        ),
        migrations.CreateModel(
            name='ausgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, max_length=100)),
                ('e_datum', models.DateField(blank=True, null=True, verbose_name='Erschienen am')),
            ],
            options={
                'verbose_name': 'Ausgabe',
                'verbose_name_plural': 'Ausgaben',
            },
        ),
        migrations.CreateModel(
            name='ausgabe_jahr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.IntegerField(choices=[(1900, '1900'), (1901, '1901'), (1902, '1902'), (1903, '1903'), (1904, '1904'), (1905, '1905'), (1906, '1906'), (1907, '1907'), (1908, '1908'), (1909, '1909'), (1910, '1910'), (1911, '1911'), (1912, '1912'), (1913, '1913'), (1914, '1914'), (1915, '1915'), (1916, '1916'), (1917, '1917'), (1918, '1918'), (1919, '1919'), (1920, '1920'), (1921, '1921'), (1922, '1922'), (1923, '1923'), (1924, '1924'), (1925, '1925'), (1926, '1926'), (1927, '1927'), (1928, '1928'), (1929, '1929'), (1930, '1930'), (1931, '1931'), (1932, '1932'), (1933, '1933'), (1934, '1934'), (1935, '1935'), (1936, '1936'), (1937, '1937'), (1938, '1938'), (1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945'), (1946, '1946'), (1947, '1947'), (1948, '1948'), (1949, '1949'), (1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017')], default=2017)),
                ('ausgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ausgabe')),
            ],
            options={
                'verbose_name': 'Jahr',
                'verbose_name_plural': 'erschienen im Jahr',
            },
        ),
        migrations.CreateModel(
            name='ausgabe_lnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lnum', models.IntegerField(default=None, verbose_name='Lfd. Nummer')),
                ('ausgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ausgabe')),
            ],
            options={
                'verbose_name': 'lfd. Nummer',
                'verbose_name_plural': 'Laufende Nummer',
            },
        ),
        migrations.CreateModel(
            name='ausgabe_monat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ausgabe')),
            ],
            options={
                'verbose_name': 'Monat',
                'verbose_name_plural': 'Monate',
            },
        ),
        migrations.CreateModel(
            name='ausgabe_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=None, verbose_name='Nummer')),
                ('ausgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ausgabe')),
            ],
            options={
                'verbose_name': 'Nummer',
                'verbose_name_plural': 'Ausgabennummer',
            },
        ),
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuerzel', models.CharField(max_length=100, verbose_name='Kürzel')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autoren',
            },
        ),
        migrations.CreateModel(
            name='band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=100, verbose_name='Bandname')),
            ],
            options={
                'verbose_name': 'Band',
                'verbose_name_plural': 'Bands',
            },
        ),
        migrations.CreateModel(
            name='band_alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default=None, max_length=100, verbose_name='Alias')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.band')),
            ],
            options={
                'verbose_name': 'Alias',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='buch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('titel_orig', models.CharField(blank=True, max_length=100, verbose_name='Titel (Original)')),
                ('jahr', models.IntegerField(blank=True, null=True)),
                ('jahr_orig', models.IntegerField(blank=True, null=True, verbose_name='Jahr (Original)')),
                ('ausgabe', models.CharField(blank=True, max_length=100)),
                ('auflage', models.CharField(blank=True, max_length=100)),
                ('buch_band', models.CharField(blank=True, max_length=100, verbose_name='Buch Band')),
                ('ubersetzer', models.CharField(blank=True, max_length=100, verbose_name='Übersetzer')),
                ('EAN', models.CharField(blank=True, max_length=100)),
                ('ISBN', models.CharField(blank=True, max_length=100)),
                ('LCCN', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Buch',
                'verbose_name_plural': 'Bücher',
            },
        ),
        migrations.CreateModel(
            name='bundesland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bland_name', models.CharField(max_length=100, verbose_name='Bundesland')),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'verbose_name': 'Bundesland',
                'verbose_name_plural': 'Bundesländer',
            },
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='genre_alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default=None, max_length=100, verbose_name='Alias')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.genre')),
            ],
            options={
                'verbose_name': 'Alias',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=100, unique=True)),
                ('kuerzel', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instrumente',
            },
        ),
        migrations.CreateModel(
            name='land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=100, unique=True, verbose_name='Land')),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'verbose_name': 'Land',
                'verbose_name_plural': 'Länder',
            },
        ),
        migrations.CreateModel(
            name='magazin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazin_name', models.CharField(max_length=100)),
                ('info', models.CharField(blank=True, max_length=100)),
                ('erstausgabe', models.DateField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, to='DBentry.genre')),
            ],
            options={
                'verbose_name': 'Magazin',
                'verbose_name_plural': 'Magazine',
            },
        ),
        migrations.CreateModel(
            name='MAP_genre_band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.band')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='MAP_genre_musiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='MAP_musiker_band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.band')),
            ],
            options={
                'verbose_name': 'Mitglied',
                'verbose_name_plural': 'Mitglieder',
            },
        ),
        migrations.CreateModel(
            name='monat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monat', models.CharField(max_length=100, verbose_name='Monat')),
                ('abk', models.CharField(max_length=100, verbose_name='Abk')),
            ],
            options={
                'verbose_name': 'Monat',
                'verbose_name_plural': 'Monate',
            },
        ),
        migrations.CreateModel(
            name='musiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuenstler_name', models.CharField(max_length=100, verbose_name='Künstlername')),
                ('genre', models.ManyToManyField(through='DBentry.MAP_genre_musiker', to='DBentry.genre')),
                ('instrument', models.ManyToManyField(to='DBentry.instrument')),
            ],
            options={
                'verbose_name': 'Musiker',
                'verbose_name_plural': 'Musiker',
            },
        ),
        migrations.CreateModel(
            name='musiker_alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default=None, max_length=100, verbose_name='Alias')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.musiker')),
            ],
            options={
                'verbose_name': 'Alias',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadt', models.CharField(max_length=100)),
                ('bland', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.bundesland')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.land')),
            ],
            options={
                'verbose_name': 'Ort',
                'verbose_name_plural': 'Orte',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(blank=True, max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('herkunft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
            },
        ),
        migrations.CreateModel(
            name='provenienz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geber', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('Schenkung', 'Schenkung'), ('Spender', 'Spende'), ('Fund', 'Fund'), ('Leihgabe', 'Leihgabe'), ('Dauerleihgabe', 'Dauerleihgabe')], default='Schenkung', max_length=100, verbose_name='Art der Provenienz')),
            ],
            options={
                'verbose_name': 'Provenienz',
                'verbose_name_plural': 'Provenienzen',
            },
        ),
        migrations.CreateModel(
            name='schlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schlagwort', models.CharField(max_length=100, unique=True)),
                ('ober', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oberschl', to='DBentry.schlagwort')),
            ],
            options={
                'verbose_name': 'Schlagwort',
                'verbose_name_plural': 'Schlagwörter',
            },
        ),
        migrations.CreateModel(
            name='schlagwort_alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default=None, max_length=100, verbose_name='Alias')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.schlagwort')),
            ],
            options={
                'verbose_name': 'Alias',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Bearbeitungsstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='turnus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnus', models.CharField(max_length=100, verbose_name='Turnus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='verlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verlag_name', models.CharField(max_length=100, verbose_name='verlag')),
                ('sitz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort')),
            ],
            options={
                'verbose_name': 'Verlag',
                'verbose_name_plural': 'Verläge',
            },
        ),
        migrations.AddField(
            model_name='musiker',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.person'),
        ),
        migrations.AddField(
            model_name='map_musiker_band',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.musiker'),
        ),
        migrations.AddField(
            model_name='map_genre_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.musiker'),
        ),
        migrations.AddField(
            model_name='magazin',
            name='turnus',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='DBentry.turnus'),
        ),
        migrations.AddField(
            model_name='magazin',
            name='verlag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.verlag'),
        ),
        migrations.AddField(
            model_name='bundesland',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.land'),
        ),
        migrations.AddField(
            model_name='buch',
            name='verlag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verlag_haupt', to='DBentry.verlag'),
        ),
        migrations.AddField(
            model_name='buch',
            name='verlag_orig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.verlag', verbose_name='Verlag (Original)'),
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(through='DBentry.MAP_genre_band', to='DBentry.genre'),
        ),
        migrations.AddField(
            model_name='band',
            name='herkunft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort'),
        ),
        migrations.AddField(
            model_name='band',
            name='mitglieder',
            field=models.ManyToManyField(through='DBentry.MAP_musiker_band', to='DBentry.musiker'),
        ),
        migrations.AddField(
            model_name='autor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.person'),
        ),
        migrations.AddField(
            model_name='ausgabe_monat',
            name='monat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.monat'),
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.magazin'),
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='provenienz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.provenienz'),
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DBentry.status'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='ausgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ausgabe'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='genre',
            field=models.ManyToManyField(to='DBentry.genre'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='schlagwort',
            field=models.ManyToManyField(to='DBentry.schlagwort'),
        ),
        migrations.AlterUniqueTogether(
            name='ort',
            unique_together=set([('stadt', 'bland', 'land')]),
        ),
        migrations.AlterUniqueTogether(
            name='bundesland',
            unique_together=set([('bland_name', 'land')]),
        ),
        migrations.AlterUniqueTogether(
            name='ausgabe_num',
            unique_together=set([('num', 'ausgabe')]),
        ),
        migrations.AlterUniqueTogether(
            name='ausgabe_monat',
            unique_together=set([('ausgabe', 'monat')]),
        ),
        migrations.AlterUniqueTogether(
            name='ausgabe_lnum',
            unique_together=set([('lnum', 'ausgabe')]),
        ),
        migrations.AlterUniqueTogether(
            name='ausgabe_jahr',
            unique_together=set([('jahr', 'ausgabe')]),
        ),
    ]
