# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='band', name='genre'), 
        migrations.RemoveField(model_name='band', name='mitglieder'), 
        migrations.RemoveField(model_name='musiker', name='genre'), 
    
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(to='DBentry.genre'),
        ),
        migrations.AddField(
            model_name='band',
            name='mitglieder',
            field=models.ManyToManyField(to='DBentry.musiker'),
        ),
        migrations.AddField(
            model_name='musiker',
            name='genre',
            field=models.ManyToManyField(to='DBentry.genre'),
        ),
    ]
