# Generated by Django 2.2.13 on 2020-08-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kalendar',
            new_name='Kalender',
        ),
    ]
