# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0002_DBentry_CNfields_ausgabe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lagerort',
            name='signatur',
        ),
        migrations.AddField(
            model_name='autor',
            name='_changed_flag',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='autor',
            name='_name',
            field=models.CharField(default='No data for %(verbose_name)s.', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='lagerort',
            name='_changed_flag',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='lagerort',
            name='_name',
            field=models.CharField(default='No data for %(verbose_name)s.', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='ort',
            name='_changed_flag',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='ort',
            name='_name',
            field=models.CharField(default='No data for %(verbose_name)s.', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='_changed_flag',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='_name',
            field=models.CharField(default='No data for %(verbose_name)s.', editable=False, max_length=200),
        ),
    ]
