# Generated by Django 2.2.13 on 2020-08-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0002_rename_kalendar_to_kalender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='band',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='musiker',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='ort',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='person',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='schlagwort',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='spielort',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='veranstaltung',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='band',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='ort',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='person',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='plattenfirma',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='schlagwort',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='spielort',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='veranstaltung',
        ),
        migrations.RemoveField(
            model_name='ausgabe',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='magazin',
        ),
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='band',
            name='musiker',
        ),
        migrations.RemoveField(
            model_name='magazin',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='magazin',
            name='herausgeber',
        ),
        migrations.RemoveField(
            model_name='magazin',
            name='verlag',
        ),
        migrations.RemoveField(
            model_name='musiker',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='musiker',
            name='instrument',
        ),
    ]
