# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0002_DBentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map_genre_band',
            name='band',
        ),
        migrations.RemoveField(
            model_name='map_genre_band',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='map_genre_musiker',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='map_genre_musiker',
            name='musiker',
        ),
        migrations.RemoveField(
            model_name='map_musiker_band',
            name='band',
        ),
        migrations.RemoveField(
            model_name='map_musiker_band',
            name='musiker',
        ),
        migrations.DeleteModel(
            name='MAP_genre_band',
        ),
        migrations.DeleteModel(
            name='MAP_genre_musiker',
        ),
        migrations.DeleteModel(
            name='MAP_musiker_band',
        ),
    ]
