# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0003_DBentry_CNmodels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['_name'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autoren'},
        ),
        migrations.AlterModelOptions(
            name='veranstaltung',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['name', 'spielort', 'datum'], 'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.RemoveField(
            model_name='veranstaltung',
            name='ort',
        ),
        migrations.AlterField(
            model_name='magazin',
            name='ausgaben_merkmal',
            field=models.CharField(blank=True, choices=[('num', 'Nummer'), ('lnum', 'Lfd.Nummer'), ('monat', 'Monat'), ('e_datum', 'Ersch.Datum')], help_text='Das dominante Merkmal der Ausgaben', max_length=200, verbose_name='Ausgaben Merkmal'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_veranstaltung_genre', to='DBentry.genre', verbose_name='Genre'),
        ),
    ]
