# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0003_DBentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('tracks', models.IntegerField()),
                ('laufzeit', models.TimeField()),
                ('festplatte', models.CharField(blank=True, max_length=100)),
                ('quelle', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='bildmaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='buch_serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='dokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='kreis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.bundesland')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lagerort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('signatur', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='memorabilien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='spielort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sprache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprache', models.CharField(max_length=100)),
                ('abk', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='technik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='veranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datum', models.DateField()),
                ('ort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort')),
                ('spielort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.spielort')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('tracks', models.IntegerField()),
                ('laufzeit', models.TimeField()),
                ('festplatte', models.CharField(blank=True, max_length=100)),
                ('quelle', models.CharField(blank=True, max_length=100)),
                ('lagerort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.lagerort')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.sender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='buch',
            name='verlag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buchverlag', to='DBentry.verlag'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='verlag_orig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buchverlagorig', to='DBentry.verlag', verbose_name='Verlag (Original)'),
        ),
        migrations.AddField(
            model_name='audio',
            name='lagerort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.lagerort'),
        ),
        migrations.AddField(
            model_name='audio',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.sender'),
        ),
        migrations.AddField(
            model_name='buch',
            name='buch_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.buch_serie', verbose_name='Buchserie'),
        ),
        migrations.AddField(
            model_name='buch',
            name='sprache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buchsprache', to='DBentry.sprache'),
        ),
        migrations.AddField(
            model_name='buch',
            name='sprache_orig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buchspracheorig', to='DBentry.sprache', verbose_name='Sprache (Original)'),
        ),
    ]
