# Generated by Django 2.2.13 on 2020-09-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0004_alias_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Audio-Medium',
                'verbose_name': 'Audio-Medium',
                'ordering': ['medium'],
                'default_permissions': ('add', 'change', 'delete', 'merge', 'view'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='medium',
            field=models.ForeignKey(blank=True, help_text='Format des Speichermediums.', null=True, on_delete=django.db.models.deletion.PROTECT, to='dbentry.AudioMedium', verbose_name='Medium'),
        ),
    ]
