# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0004_DBentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name': 'Audio Material', 'verbose_name_plural': 'Audio Materialien'},
        ),
        migrations.AlterModelOptions(
            name='ausgabe_jahr',
            options={'verbose_name': 'Jahr', 'verbose_name_plural': 'Jahre'},
        ),
        migrations.AlterModelOptions(
            name='bildmaterial',
            options={'verbose_name': 'Bild Material', 'verbose_name_plural': 'Bild Materialien'},
        ),
        migrations.AlterModelOptions(
            name='buch_serie',
            options={'verbose_name': 'Buchserie', 'verbose_name_plural': 'Buchserien'},
        ),
        migrations.AlterModelOptions(
            name='dokument',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumente'},
        ),
        migrations.AlterModelOptions(
            name='kreis',
            options={'verbose_name': 'Kreis', 'verbose_name_plural': 'Kreise'},
        ),
        migrations.AlterModelOptions(
            name='lagerort',
            options={'verbose_name': 'Lagerort', 'verbose_name_plural': 'Lagerorte'},
        ),
        migrations.AlterModelOptions(
            name='memorabilien',
            options={'verbose_name': 'Memorabilia', 'verbose_name_plural': 'Memorabilien'},
        ),
        migrations.AlterModelOptions(
            name='sender',
            options={'verbose_name': 'Sender', 'verbose_name_plural': 'Sender'},
        ),
        migrations.AlterModelOptions(
            name='spielort',
            options={'verbose_name': 'Spielort', 'verbose_name_plural': 'Spielorte'},
        ),
        migrations.AlterModelOptions(
            name='sprache',
            options={'verbose_name': 'Sprache', 'verbose_name_plural': 'Sprachen'},
        ),
        migrations.AlterModelOptions(
            name='technik',
            options={'verbose_name': 'Technik', 'verbose_name_plural': 'Technik'},
        ),
        migrations.AlterModelOptions(
            name='veranstaltung',
            options={'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video Material', 'verbose_name_plural': 'Video Materialien'},
        ),
        migrations.AddField(
            model_name='artikel',
            name='person',
            field=models.ManyToManyField(to='DBentry.person'),
        ),
    ]
