# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0004_DBentry_ModelRework_01'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datei',
            name='band',
        ),
        migrations.RemoveField(
            model_name='datei',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='datei',
            name='ort',
        ),
        migrations.RemoveField(
            model_name='datei',
            name='person',
        ),
        migrations.RemoveField(
            model_name='datei',
            name='schlagwort',
        ),
        migrations.RemoveField(
            model_name='datei',
            name='spielort',
        ),
        migrations.RemoveField(
            model_name='datei',
            name='veranstaltung',
        ),
        migrations.RemoveField(
            model_name='veranstaltung',
            name='band',
        ),
        migrations.RemoveField(
            model_name='veranstaltung',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='veranstaltung',
            name='person',
        ),
        migrations.RemoveField(
            model_name='video',
            name='band',
        ),
        migrations.RemoveField(
            model_name='video',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='video',
            name='person',
        ),
        migrations.RemoveField(
            model_name='video',
            name='schlagwort',
        ),
        migrations.RemoveField(
            model_name='video',
            name='spielort',
        ),
        migrations.RemoveField(
            model_name='video',
            name='veranstaltung',
        ),
        migrations.RemoveField(
            model_name='buch',
            name='autor',
        ),
    ]
