# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0005_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='autor',
            field=models.ManyToManyField(to='DBentry.autor'),
        ),
    ]
