# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0006_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='band',
            field=models.ManyToManyField(to='DBentry.band'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='musiker',
            field=models.ManyToManyField(to='DBentry.musiker'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='ort',
            field=models.ManyToManyField(to='DBentry.ort'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='spielort',
            field=models.ManyToManyField(to='DBentry.spielort'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='veranstaltung',
            field=models.ManyToManyField(to='DBentry.veranstaltung'),
        ),
    ]
