# Generated by Django 2.2.13 on 2020-09-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0006_data_formate_to_audio_medium'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Format',
        ),
        migrations.DeleteModel(
            name='FormatSize',
        ),
        migrations.DeleteModel(
            name='FormatTag',
        ),
        migrations.DeleteModel(
            name='FormatTyp',
        ),
    ]
