# Generated by Django 2.2.13 on 2020-09-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0007_delete_format_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='catalog_nr',
            new_name='plattennummer',
        ),
        migrations.AlterField(
            model_name='audio',
            name='plattennummer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
