# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 11:01
from __future__ import unicode_literals

import DBentry.fields
import DBentry.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0007_DBentry_ModelRework_04_m2mFieldReadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='m2m_video_musiker',
            name='instrument',
            field=models.ManyToManyField(blank=True, to='DBentry.instrument', verbose_name='Instrumente'),
        ),
        migrations.AddField(
            model_name='magazin',
            name='fanzine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magazin',
            name='issn',
            field=DBentry.fields.ISSNField(blank=True, max_length=8, validators=[DBentry.validators.ISSNValidator], verbose_name='ISSN'),
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='status',
            field=models.CharField(choices=[('unb', 'unbearbeitet'), ('iB', 'in Bearbeitung'), ('abg', 'abgeschlossen'), ('kB', 'keine Bearbeitung vorgesehen')], default=1, max_length=40, verbose_name='Bearbeitungsstatus'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='datum',
            field=models.DateField(blank=True, help_text='Format: tt.mm.jjjj', null=True),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='erstausgabe',
            field=models.DateField(blank=True, help_text='Format: tt.mm.jjjj', null=True),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='datum',
            field=models.DateField(help_text='Format: tt.mm.jjjj'),
        ),
    ]
