# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0007_DBentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='zusammenfassung',
            field=models.TextField(blank=True),
        ),
    ]
