# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0008_DBentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausgabe_jahr',
            options={'ordering': ['jahr'], 'verbose_name': 'Jahr', 'verbose_name_plural': 'Jahre'},
        ),
        migrations.AlterModelOptions(
            name='magazin',
            options={'ordering': ['magazin_name'], 'verbose_name': 'Magazin', 'verbose_name_plural': 'Magazine'},
        ),
        migrations.AlterField(
            model_name='buch',
            name='jahr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buch',
            name='jahr_orig',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Jahr (Original)'),
        ),
    ]
