# Generated by Django 2.2.16 on 2020-10-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0009_remove_m2m_through'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestand',
            name='bestand_art',
        ),
    ]
