# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0009_DBentry_ModelRework_06'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='info',
            new_name='beschreibung',
        ),
        migrations.RenameField(
            model_name='ausgabe',
            old_name='info',
            new_name='beschreibung',
        ),
        migrations.RenameField(
            model_name='magazin',
            old_name='info',
            new_name='bemerkungen',
        ),
    ]
