# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 07:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0009_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='buch',
            name='autor',
            field=models.ManyToManyField(to='DBentry.autor'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='jahr',
            field=models.PositiveIntegerField(blank=True, default=2017, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)]),
        ),
        migrations.AlterField(
            model_name='buch',
            name='jahr_orig',
            field=models.PositiveIntegerField(blank=True, default=2017, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)], verbose_name='Jahr (Original)'),
        ),
    ]
