# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 08:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0010_DBentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgabe',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='kuerzel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kürzel'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='jahr',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)]),
        ),
        migrations.AlterField(
            model_name='buch',
            name='jahr_orig',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)], verbose_name='Jahr (Original)'),
        ),
    ]
