# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0010_DBentry_ModelRework_07_InfoFieldRename'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='audio',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Mediums'),
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='autor',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='autor',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Autors'),
        ),
        migrations.AddField(
            model_name='band',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='bildmaterial',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='bildmaterial',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Bildmaterials'),
        ),
        migrations.AddField(
            model_name='buch',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='buch',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Buches'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Dokumentes'),
        ),
        migrations.AddField(
            model_name='memorabilien',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='memorabilien',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Memorabiliums'),
        ),
        migrations.AddField(
            model_name='musiker',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='person',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='technik',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='technik',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. der Technik'),
        ),
        migrations.AddField(
            model_name='video',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='video',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Mediums'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Artikels'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. der Ausgabe'),
        ),
        migrations.AlterField(
            model_name='band',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. der Band'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. der Datei'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Magazines'),
        ),
        migrations.AlterField(
            model_name='musiker',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Musikers'),
        ),
        migrations.AlterField(
            model_name='person',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. der Person'),
        ),
    ]
