# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0011_DBentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgabe',
            name='status',
            field=models.CharField(choices=[('unb', 'unbearbeitet'), ('iB', 'in Bearbeitung'), ('abg', 'abgeschlossen')], default=1, max_length=40),
        ),
    ]
