# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0012_DBentry_ModelRework_09_OnDelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='orte',
            field=models.ManyToManyField(blank=True, to='DBentry.ort'),
        ),
        migrations.AddField(
            model_name='band',
            name='orte',
            field=models.ManyToManyField(blank=True, to='DBentry.ort'),
        ),
        migrations.AddField(
            model_name='musiker',
            name='orte',
            field=models.ManyToManyField(blank=True, to='DBentry.ort'),
        ),
        migrations.AddField(
            model_name='person',
            name='orte',
            field=models.ManyToManyField(blank=True, to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='band',
            name='herkunft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bands', to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='person',
            name='herkunft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personen', to='DBentry.ort'),
        ),
    ]
