# Generated by Django 2.2.16 on 2020-10-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0012_audio_video_tweaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='original',
            field=models.BooleanField(default=False, help_text='Ist das vorliegende Material ein Original?', verbose_name='Originalmaterial'),
        ),
        migrations.AlterField(
            model_name='video',
            name='original',
            field=models.BooleanField(default=False, help_text='Ist das vorliegende Material ein Original?', verbose_name='Originalmaterial'),
        ),
    ]
