# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0012_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='ober',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obergenre', to='DBentry.genre', verbose_name='Oberbegriff'),
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='info',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ort',
            name='bland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.bundesland', verbose_name='Bundesland'),
        ),
        migrations.AlterField(
            model_name='schlagwort',
            name='ober',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oberschl', to='DBentry.schlagwort', verbose_name='Oberbegriff'),
        ),
    ]
