# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0013_DBentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='laufzeit',
            field=models.DurationField(),
        ),
    ]
