# Generated by Django 2.2.16 on 2020-10-28 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0014_add_discogs_to_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='medium_qty',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Anzahl'),
        ),
        migrations.AlterField(
            model_name='video',
            name='medium_qty',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Anzahl'),
        ),
    ]
