# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0014_DBentry_ModelRework_11_OrteM2MData'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
        migrations.RemoveField(
            model_name='band',
            name='herkunft',
        ),
        migrations.RemoveField(
            model_name='person',
            name='herkunft',
        ),
    ]
