# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0015_DBentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazin',
            name='turnus',
            field=models.CharField(blank=True, choices=[('u', 'unbekannt'), ('t', 'täglich'), ('w', 'wöchentlich'), ('2w', 'zwei-wöchentlich'), ('m', 'monatlich'), ('2m', 'zwei-monatlich'), ('q', 'quartalsweise'), ('hj', 'halbjährlich'), ('j', 'jährlich')], default=5, max_length=100),
        ),
    ]
