# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0016_DBentry_ModelRework_13_RemovedAutorOrte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='format_name',
        ),
        migrations.AddField(
            model_name='format',
            name='_changed_flag',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='format',
            name='_name',
            field=models.CharField(default='No data for %(verbose_name)s.', editable=False, max_length=200),
        ),
    ]
