# Generated by Django 2.2.16 on 2020-11-27 13:02
# Remove the 'alter_bestand_<model>' model permissions.

from django.db import migrations, transaction


@transaction.atomic
def delete_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.filter(codename__startswith='alter_bestand').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0016_alter_video_medium_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'verbose_name': 'Audio Material', 'verbose_name_plural': 'Audio Materialien'},
        ),
        migrations.AlterModelOptions(
            name='ausgabe',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['magazin'], 'verbose_name': 'Ausgabe', 'verbose_name_plural': 'Ausgaben'},
        ),
        migrations.AlterModelOptions(
            name='bildmaterial',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'verbose_name': 'Bild Material', 'verbose_name_plural': 'Bild Materialien'},
        ),
        migrations.AlterModelOptions(
            name='buch',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'verbose_name': 'Buch', 'verbose_name_plural': 'Bücher'},
        ),
        migrations.AlterModelOptions(
            name='dokument',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumente'},
        ),
        migrations.AlterModelOptions(
            name='memorabilien',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'verbose_name': 'Memorabilia', 'verbose_name_plural': 'Memorabilien'},
        ),
        migrations.AlterModelOptions(
            name='technik',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'verbose_name': 'Technik', 'verbose_name_plural': 'Technik'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'verbose_name': 'Video Material', 'verbose_name_plural': 'Video Materialien'},
        ),
        migrations.RunPython(delete_permissions, migrations.RunPython.noop)
    ]
