# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0016_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazin',
            name='ort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort', verbose_name='Hrsg.Ort'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='turnus',
            field=models.CharField(blank=True, choices=[('u', 'unbekannt'), ('t', 'täglich'), ('w', 'wöchentlich'), ('w2', 'zwei-wöchentlich'), ('m', 'monatlich'), ('m2', 'zwei-monatlich'), ('q', 'quartalsweise'), ('hj', 'halbjährlich'), ('j', 'jährlich')], default='m', max_length=100),
        ),
    ]
