# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0017_DBentry_ModelRework_14_FormatCNModel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.person'),
        ),
    ]
