# Generated by Django 2.2.16 on 2020-12-04 09:26
# Children of BaseBrochure now inherit its Meta too. This adds
# 'default_permissions' to their Meta classes (from BaseModel.Meta).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0017_removed_alter_bestand_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brochure',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'verbose_name': 'Broschüre', 'verbose_name_plural': 'Broschüren'},
        ),
        migrations.AlterModelOptions(
            name='kalender',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'verbose_name': 'Programmheft', 'verbose_name_plural': 'Programmhefte'},
        ),
        migrations.AlterModelOptions(
            name='katalog',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'verbose_name': 'Warenkatalog', 'verbose_name_plural': 'Warenkataloge'},
        ),
    ]
