# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0017_DBentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ort',
            name='stadt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
