# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0018_DBentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='instrument_alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default=None, max_length=100, verbose_name='Alias')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.instrument')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Alias',
            },
        ),
        migrations.CreateModel(
            name='land_alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default=None, max_length=100, verbose_name='Alias')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.land')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Alias',
            },
        ),
        migrations.CreateModel(
            name='sender_alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default=None, max_length=100, verbose_name='Alias')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.sender')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Alias',
            },
        ),
        migrations.CreateModel(
            name='spielort_alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default=None, max_length=100, verbose_name='Alias')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.spielort')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Alias',
            },
        ),
        migrations.CreateModel(
            name='veranstaltung_alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default=None, max_length=100, verbose_name='Alias')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.veranstaltung')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Alias',
            },
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.magazin', verbose_name='Magazin'),
        ),
    ]
