# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0018_DBentry_ModelRework_15_AutorOptionalPerson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nachname',
            field=models.CharField(max_length=200),
        ),
    ]
