# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0019_DBentry_ModelRework_16_RemovedPersonNachnameDefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='lagerort',
            name='fach',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lagerort',
            name='ordner',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
