# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 06:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0020_ModelsRework_17_lagerort_additions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgabe',
            name='jahrgang',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Jahrgang'),
        ),
    ]
