# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0020_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='magazin',
            name='magazin_url',
            field=models.URLField(blank=True),
        ),
    ]
