# Generated by Django 2.2.16 on 2021-04-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0020_ausgabe_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bildmaterial',
            new_name='Plakat',
        ),
        migrations.AlterModelOptions(
            name='plakat',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'verbose_name': 'Plakat', 'verbose_name_plural': 'Plakate'},
        ),
        migrations.RenameField(
            model_name='bestand',
            old_name='bildmaterial',
            new_name='plakat',
        ),
        migrations.RenameField(
            model_name='m2m_datei_quelle',
            old_name='bildmaterial',
            new_name='plakat',
        ),
        migrations.AlterField(
            model_name='plakat',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Plakates'),
        ),
    ]
