# Generated by Django 2.2.16 on 2021-03-09 13:04

import dbentry.db.base
from django.db import migrations
import tsvector_field


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0020_ausgabe_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='search',
            field=dbentry.db.base.SearchVectorField(blank=True, columns=[dbentry.db.base.WeightedColumn('band_name', 'A', 'simple'), dbentry.db.base.WeightedColumn('beschreibung', 'C', 'german')], editable=False, language='simple'),
        ),
        tsvector_field.IndexSearchVector('band', 'search'),
        migrations.AddField(
            model_name='bandalias',
            name='search',
            field=dbentry.db.base.SearchVectorField(blank=True, columns=[dbentry.db.base.WeightedColumn('alias', 'B', 'simple')], editable=False, language='simple'),
        ),
        tsvector_field.IndexSearchVector('bandalias', 'search'),
    ]
