# Generated by Django 2.2.16 on 2021-04-06 09:50

import dbentry.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0021_rename_bildmaterial_plakat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, max_length=200, verbose_name='Größe')),
                ('datum', dbentry.fields.PartialDateField(blank=True, help_text='Teilweise Angaben sind erlaubt (z.B. Jahr & Monat aber ohne Tag).', max_length=10, verbose_name='Zeitangabe')),
                ('typ', models.CharField(choices=[('negativ', 'negativ'), ('positiv', 'positiv'), ('reprint', 'Neuabzug (reprint)'), ('polaroid', 'Polaroid')], default='negativ', max_length=100, verbose_name='Art des Fotos')),
                ('farbe', models.BooleanField(verbose_name='Farbfoto')),
                ('owner', models.CharField(blank=True, max_length=200, verbose_name='Rechteinhaber')),
                ('beschreibung', models.TextField(blank=True, help_text='Beschreibung bzgl. des Fotos')),
                ('bemerkungen', models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter')),
                ('band', models.ManyToManyField(to='dbentry.Band')),
                ('genre', models.ManyToManyField(to='dbentry.Genre')),
                ('musiker', models.ManyToManyField(to='dbentry.Musiker')),
                ('ort', models.ManyToManyField(to='dbentry.Ort')),
                ('person', models.ManyToManyField(to='dbentry.Person')),
                ('reihe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dbentry.Bildreihe', verbose_name='Bildreihe')),
                ('schlagwort', models.ManyToManyField(to='dbentry.Schlagwort')),
                ('spielort', models.ManyToManyField(to='dbentry.Spielort')),
                ('veranstaltung', models.ManyToManyField(to='dbentry.Veranstaltung')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'merge', 'view'),
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['titel'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bestand',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbentry.Foto'),
        ),
    ]
