# Generated by Django 2.2.16 on 2021-08-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0022_add_model_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dnb_url',
            field=models.URLField(blank=True, help_text='Adresse zur Seite dieser Person in der Deutschen Nationalbibliothek.', verbose_name='Link DNB'),
        ),
        migrations.AddField(
            model_name='person',
            name='gnd_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Normdatei ID'),
        ),
        migrations.AddField(
            model_name='person',
            name='gnd_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Normdatei Name'),
        ),
    ]
