# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0022_DBentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausgabe',
            options={'ordering': ['magazin'], 'verbose_name': 'Ausgabe', 'verbose_name_plural': 'Ausgaben'},
        ),
        migrations.AlterModelOptions(
            name='ausgabe_lnum',
            options={'ordering': ['lnum'], 'verbose_name': 'lfd. Nummer', 'verbose_name_plural': 'Laufende Nummer'},
        ),
        migrations.AlterModelOptions(
            name='ausgabe_monat',
            options={'ordering': ['monat'], 'verbose_name': 'Monat', 'verbose_name_plural': 'Monate'},
        ),
        migrations.AlterModelOptions(
            name='ausgabe_num',
            options={'ordering': ['num'], 'verbose_name': 'Nummer', 'verbose_name_plural': 'Ausgabennummer'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['person__vorname', 'person__nachname'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autoren'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['genre'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='memorabilien',
            options={'ordering': ['titel'], 'verbose_name': 'Memorabilia', 'verbose_name_plural': 'Memorabilien'},
        ),
        migrations.AlterModelOptions(
            name='monat',
            options={'ordering': ['id'], 'verbose_name': 'Monat', 'verbose_name_plural': 'Monate'},
        ),
        migrations.AlterModelOptions(
            name='musiker',
            options={'ordering': ['kuenstler_name', 'person'], 'verbose_name': 'Musiker', 'verbose_name_plural': 'Musiker'},
        ),
        migrations.AlterModelOptions(
            name='ort',
            options={'ordering': ['land', 'bland', 'stadt'], 'verbose_name': 'Ort', 'verbose_name_plural': 'Orte'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['nachname', 'vorname', 'herkunft'], 'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
        migrations.AlterModelOptions(
            name='provenienz',
            options={'ordering': ['geber', 'typ'], 'verbose_name': 'Provenienz', 'verbose_name_plural': 'Provenienzen'},
        ),
        migrations.AlterModelOptions(
            name='schlagwort',
            options={'ordering': ['schlagwort'], 'verbose_name': 'Schlagwort', 'verbose_name_plural': 'Schlagwörter'},
        ),
        migrations.AlterModelOptions(
            name='sender',
            options={'ordering': ['name'], 'verbose_name': 'Sender', 'verbose_name_plural': 'Sender'},
        ),
        migrations.AlterModelOptions(
            name='spielort',
            options={'ordering': ['name'], 'verbose_name': 'Spielort', 'verbose_name_plural': 'Spielorte'},
        ),
        migrations.AlterModelOptions(
            name='sprache',
            options={'ordering': ['sprache'], 'verbose_name': 'Sprache', 'verbose_name_plural': 'Sprachen'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': None},
        ),
        migrations.AlterModelOptions(
            name='technik',
            options={'ordering': ['titel'], 'verbose_name': 'Technik', 'verbose_name_plural': 'Technik'},
        ),
        migrations.AlterModelOptions(
            name='turnus',
            options={'ordering': None},
        ),
        migrations.AlterModelOptions(
            name='veranstaltung',
            options={'ordering': ['name', 'spielort', 'ort', 'datum'], 'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.AlterModelOptions(
            name='verlag',
            options={'ordering': ['verlag_name', 'sitz'], 'verbose_name': 'Verlag', 'verbose_name_plural': 'Verläge'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['titel'], 'verbose_name': 'Video Material', 'verbose_name_plural': 'Video Materialien'},
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='bands',
            field=models.ManyToManyField(blank=True, null=True, to='DBentry.band', verbose_name='Teilnehmer (Bands)'),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='DBentry.genre'),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='personen',
            field=models.ManyToManyField(blank=True, null=True, to='DBentry.person', verbose_name='Teilnehmer (Personen)'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='seitenumfang',
            field=models.CharField(blank=True, choices=[(None, ''), ('f', 'f'), ('ff', 'ff')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='status',
            field=models.CharField(choices=[('unb', 'unbearbeitet'), ('iB', 'in Bearbeitung'), ('abg', 'abgeschlossen')], default=1, max_length=40, verbose_name='Bearbeitungsstatus'),
        ),
        migrations.AlterField(
            model_name='ausgabe_jahr',
            name='jahr',
            field=models.IntegerField(choices=[(1900, '1900'), (1901, '1901'), (1902, '1902'), (1903, '1903'), (1904, '1904'), (1905, '1905'), (1906, '1906'), (1907, '1907'), (1908, '1908'), (1909, '1909'), (1910, '1910'), (1911, '1911'), (1912, '1912'), (1913, '1913'), (1914, '1914'), (1915, '1915'), (1916, '1916'), (1917, '1917'), (1918, '1918'), (1919, '1919'), (1920, '1920'), (1921, '1921'), (1922, '1922'), (1923, '1923'), (1924, '1924'), (1925, '1925'), (1926, '1926'), (1927, '1927'), (1928, '1928'), (1929, '1929'), (1930, '1930'), (1931, '1931'), (1932, '1932'), (1933, '1933'), (1934, '1934'), (1935, '1935'), (1936, '1936'), (1937, '1937'), (1938, '1938'), (1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945'), (1946, '1946'), (1947, '1947'), (1948, '1948'), (1949, '1949'), (1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017')], default=2017, verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='bundesland',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.land', verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='magazin_name',
            field=models.CharField(max_length=100, verbose_name='Magazin'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.land', verbose_name='Land'),
        ),
    ]
