# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 09:44
from __future__ import unicode_literals

import DBentry.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0022_add_monat_ordinal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buch',
            name='LCCN',
        ),
        migrations.RemoveField(
            model_name='buch',
            name='ausgabe',
        ),
        migrations.RemoveField(
            model_name='buch',
            name='buch_band',
        ),
        migrations.RemoveField(
            model_name='buch',
            name='buch_serie',
        ),
        migrations.RemoveField(
            model_name='buch',
            name='sprache_orig',
        ),
        migrations.RemoveField(
            model_name='buch',
            name='ubersetzer',
        ),
        migrations.RemoveField(
            model_name='buch',
            name='verlag_orig',
        ),
        migrations.AddField(
            model_name='buch',
            name='buchband',
            field=models.ForeignKey(blank=True, help_text='Der Buchband, der diesen Aufsatz enthält.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buch_set', to='DBentry.buch'),
        ),
        migrations.AddField(
            model_name='buch',
            name='is_buchband',
            field=models.BooleanField(default=False, help_text='Dieses Buch ist ein Buchband bestehend aus Aufsätzen.', verbose_name='Ist Buchband'),
        ),
        migrations.AddField(
            model_name='buch',
            name='seitenumfang',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buch',
            name='EAN',
            field=DBentry.fields.EANField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='buch',
            name='ISBN',
            field=DBentry.fields.ISBNField(blank=True, max_length=17),
        ),
    ]
