# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0023_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='beschreibung',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='musiker',
            name='beschreibung',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='seitenumfang',
            field=models.CharField(blank=True, choices=[('f', 'f'), ('ff', 'ff')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='bands',
            field=models.ManyToManyField(to='DBentry.band', verbose_name='Teilnehmer (Bands)'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='genres',
            field=models.ManyToManyField(to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='personen',
            field=models.ManyToManyField(to='DBentry.person', verbose_name='Teilnehmer (Personen)'),
        ),
    ]
