# Generated by Django 2.2.16 on 2021-08-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0023_person_gnd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgabe',
            name='e_datum',
            field=models.DateField(blank=True, help_text='Format: TT.MM.JJJJ oder JJJJ-MM-TT (ISO 8601)', null=True, verbose_name='Erscheinungsdatum'),
        ),
    ]
