# Generated by Django 2.2.16 on 2021-08-23 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0024_ausgabe_e_datum_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeranstaltungURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Webpage')),
                ('brochure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='dbentry.Veranstaltung')),
            ],
            options={
                'verbose_name': 'Web-Adresse',
                'verbose_name_plural': 'Web-Adressen',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'merge', 'view'),
            },
        ),
        migrations.CreateModel(
            name='SpielortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Webpage')),
                ('brochure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='dbentry.Spielort')),
            ],
            options={
                'verbose_name': 'Web-Adresse',
                'verbose_name_plural': 'Web-Adressen',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'merge', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PersonURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Webpage')),
                ('brochure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='dbentry.Person')),
            ],
            options={
                'verbose_name': 'Web-Adresse',
                'verbose_name_plural': 'Web-Adressen',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'merge', 'view'),
            },
        ),
        migrations.CreateModel(
            name='MusikerURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Webpage')),
                ('brochure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='dbentry.Musiker')),
            ],
            options={
                'verbose_name': 'Web-Adresse',
                'verbose_name_plural': 'Web-Adressen',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'merge', 'view'),
            },
        ),
        migrations.CreateModel(
            name='BandURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Webpage')),
                ('brochure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='dbentry.Band')),
            ],
            options={
                'verbose_name': 'Web-Adresse',
                'verbose_name_plural': 'Web-Adressen',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'merge', 'view'),
            },
        ),
        migrations.CreateModel(
            name='AutorURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Webpage')),
                ('brochure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='dbentry.Autor')),
            ],
            options={
                'verbose_name': 'Web-Adresse',
                'verbose_name_plural': 'Web-Adressen',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'merge', 'view'),
            },
        ),
    ]
