# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0025_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='original_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
