# Generated by Django 3.2.11 on 2022-01-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0027_fts_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestand',
            name='anmerkungen',
            field=models.TextField(blank=True),
        ),
    ]
