# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0027_add_model_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herausgeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(default='No data for %(verbose_name)s.', editable=False, max_length=200)),
                ('_changed_flag', models.BooleanField(default=False, editable=False)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.Organisation')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.person')),
            ],
            options={
                'verbose_name': 'Herausgeber',
                'verbose_name_plural': 'Herausgeber',
                'abstract': False,
                'ordering': ['_name'],
                'default_permissions': ('add', 'change', 'delete', 'merge'),
            },
        ),
    ]
