# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0028_add_model_herausgeber'),
    ]

    operations = [
        migrations.AddField(
            model_name='buch',
            name='herausgeber',
            field=models.ManyToManyField(to='DBentry.Herausgeber'),
        ),
    ]
