# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0028_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='magazin',
            field=models.ManyToManyField(to='DBentry.magazin'),
        ),
    ]
