# Generated by Django 3.2.11 on 2022-01-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0028_bestand_anmerkungen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbentry.person'),
        ),
    ]
