# Generated by Django 3.2.11 on 2022-02-15 09:39

import dbentry.fts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0029_alter_autor_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestand',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(columns=[dbentry.fts.fields.WeightedColumn('anmerkungen', 'A', 'german_unaccent')]),
        ),
    ]
