# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0029_DBentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='bestand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ausgabe')),
                ('buch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.buch')),
                ('provenienz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.provenienz')),
            ],
        ),
        migrations.AlterField(
            model_name='autor',
            name='magazin',
            field=models.ManyToManyField(blank=True, to='DBentry.magazin'),
        ),
    ]
