# Generated by Django 4.1.7 on 2023-06-07 08:02

import dbentry.fields
import dbentry.fts.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dbentry", "0030_bestand_text_search_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.TextField(max_length=200)),
                ("zusammenfassung", models.TextField(blank=True)),
                (
                    "anmerkungen",
                    models.TextField(blank=True, help_text="Weitere Anmerkungen"),
                ),
                (
                    "_fts",
                    dbentry.fts.fields.SearchVectorField(
                        columns=[
                            dbentry.fts.fields.WeightedColumn(
                                "titel", "A", "simple_unaccent"
                            ),
                            dbentry.fts.fields.WeightedColumn(
                                "zusammenfassung", "B", "german_unaccent"
                            ),
                            dbentry.fts.fields.WeightedColumn(
                                "anmerkungen", "D", "simple_unaccent"
                            ),
                        ]
                    ),
                ),
                (
                    "ausgabe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printmedia",
                        to="dbentry.ausgabe",
                        verbose_name="Ausgabe",
                    ),
                ),
                ("genre", models.ManyToManyField(to="dbentry.genre")),
                ("schlagwort", models.ManyToManyField(to="dbentry.schlagwort")),
                ("spielort", models.ManyToManyField(to="dbentry.spielort")),
            ],
            options={
                "verbose_name": "Druckerzeugnis",
                "verbose_name_plural": "Druckerzeugnisse",
                "ordering": ["titel"],
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "merge", "view"),
            },
        ),
        migrations.CreateModel(
            name="PrintMediaType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typ", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "merge", "view"),
            },
        ),
        migrations.CreateModel(
            name="PrintMediaYear",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jahr", dbentry.fields.YearField(verbose_name="Jahr")),
                (
                    "PrintMedia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jahre",
                        to="dbentry.printmedia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jahr",
                "verbose_name_plural": "Jahre",
                "ordering": ["jahr"],
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "merge", "view"),
            },
        ),
        migrations.CreateModel(
            name="PrintMediaURL",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Webpage")),
                (
                    "PrintMedia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="dbentry.printmedia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webseite",
                "verbose_name_plural": "Webseiten",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "merge", "view"),
            },
        ),
        migrations.AddField(
            model_name="printmedia",
            name="typ",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="printmedia",
                to="dbentry.printmediatype",
            ),
        ),
        migrations.AddField(
            model_name="printmedia",
            name="veranstaltung",
            field=models.ManyToManyField(to="dbentry.veranstaltung"),
        ),
        migrations.AddField(
            model_name="bestand",
            name="printmedia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dbentry.printmedia",
            ),
        ),
    ]
