# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0030_DBentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='geber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'ordering': ['name'],
            },
        ),
    ]
