# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

# Add m2m models for magazin_verlag and magazin_herausgeber

class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0030_alter_autor_and_buch'),
    ]

    operations = [
        migrations.CreateModel(
            name='m2m_magazin_herausgeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, max_length=123, verbose_name='von')),
                ('end', models.CharField(blank=True, max_length=123, verbose_name='bis')),
                ('herausgeber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Herausgeber')),
                ('magazin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.magazin')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'merge'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='m2m_magazin_verlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, max_length=123, verbose_name='von')),
                ('end', models.CharField(blank=True, max_length=123, verbose_name='bis')),
                ('magazin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.magazin')),
                ('verlag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.verlag')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'merge'),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='m2m_magazin_herausgeber',
            options={'verbose_name': 'Magazin-Herausgeber', 'verbose_name_plural': 'Magazin-Herausgeber'},
        ),
        migrations.AlterModelOptions(
            name='m2m_magazin_verlag',
            options={'verbose_name': 'Magazin-Verlag', 'verbose_name_plural': 'Magazin-Verlage'},
        ),
        migrations.AlterUniqueTogether(
            name='m2m_magazin_herausgeber',
            unique_together=set([('magazin', 'herausgeber')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_magazin_verlag',
            unique_together=set([('magazin', 'verlag')]),
        ),
    ]
