# Generated by Django 4.2.9 on 2024-04-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbentry", "0030_bestand_text_search_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autorurl",
            name="url",
            field=models.URLField(verbose_name="Webpage"),
        ),
        migrations.AlterField(
            model_name="bandurl",
            name="url",
            field=models.URLField(verbose_name="Webpage"),
        ),
        migrations.AlterField(
            model_name="brochureurl",
            name="url",
            field=models.URLField(verbose_name="Webpage"),
        ),
        migrations.AlterField(
            model_name="magazinurl",
            name="url",
            field=models.URLField(verbose_name="Webpage"),
        ),
        migrations.AlterField(
            model_name="musikerurl",
            name="url",
            field=models.URLField(verbose_name="Webpage"),
        ),
        migrations.AlterField(
            model_name="personurl",
            name="url",
            field=models.URLField(verbose_name="Webpage"),
        ),
        migrations.AlterField(
            model_name="spielorturl",
            name="url",
            field=models.URLField(verbose_name="Webpage"),
        ),
        migrations.AlterField(
            model_name="veranstaltungurl",
            name="url",
            field=models.URLField(verbose_name="Webpage"),
        ),
    ]
