# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0031_DBentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenienz',
            name='geber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.geber'),
        ),
    ]
