# Generated by Django 4.1.7 on 2023-06-07 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dbentry", "0031_printmedia_printmediatype_printmediayear_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printmediatype",
            options={
                "verbose_name": "Druckerzeugnistyp",
                "verbose_name_plural": "Druckerzeugnistypen",
            },
        ),
    ]
