# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 09:32
from __future__ import unicode_literals

from django.db import migrations

# Migrates the data from the ForeignKey field magazin.verlag to the new m2m model for magazin_verlag

def forwards_func(apps, schema_editor):
    magazin = apps.get_model('DBentry','magazin')
    magazin_verlag = apps.get_model('DBentry', 'm2m_magazin_verlag')
    db_alias = schema_editor.connection.alias
    
    objects =  []
    for pk, verlag_id in magazin.objects.using(db_alias).exclude(verlag__isnull=True).values_list('pk','verlag_id'):
        objects.append(magazin_verlag(magazin_id=pk, verlag_id=verlag_id))
    
    magazin_verlag.objects.using(db_alias).bulk_create(objects)
    
    

def reverse_func(apps, schema_editor):
    magazin = apps.get_model('DBentry','magazin')
    magazin_verlag = apps.get_model('DBentry', 'm2m_magazin_verlag')
    db_alias = schema_editor.connection.alias
    for magazin_id, verlag_id in magazin_verlag.objects.values_list('magazin_id','verlag_id'):
        magazin.objects.using(db_alias).filter(pk=magazin_id).update(verlag_id=verlag_id)

class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0031_add_m2m_magazin_verlag_herausgeber'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func), 
    ]
