# Generated by Django 4.1.9 on 2023-06-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dbentry", "0031_add_printmedia_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printmedia",
            name="_brochure_ptr",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dbentry.basebrochure",
            ),
        ),
    ]
