# Generated by Django 3.2.14 on 2022-07-08 09:22
from functools import partial

from django.contrib.postgres.search import SearchVector
from django.db.migrations import RunPython
from django.db.models import F

import dbentry.fts.fields
import django.contrib.postgres.indexes
from django.db import migrations


def get_vector(search_field):
    vector = None
    for column in search_field.columns:
        v = SearchVector(F(column.name), weight=column.weight, config=column.config)
        if vector is None:
            vector = v
        else:
            vector += v
    return vector


def update_index(model_name, field_name, apps, _schema_editor):
    model = apps.get_model('dbentry', model_name)
    search_field = model._meta.get_field(field_name)
    vector = get_vector(search_field)
    model.objects.update(**{search_field.name: vector})


class IndexSearchVector(RunPython):

    def __init__(self, model_name, field_name):
        code = partial(update_index, model_name, field_name)
        super().__init__(code, reverse_code=RunPython.noop)


class Migration(migrations.Migration):

    dependencies = [
        ('dbentry', '0031_remove_fts_indexes_and_triggers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandalias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genrealias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='musikeralias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='schlagwortalias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spielortalias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='veranstaltungalias',
            options={},
        ),
        migrations.AlterField(
            model_name='artikel',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('schlagzeile', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('zusammenfassung', 'B', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('titel', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='audiomedium',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('medium', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('_name', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('_name', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('band_name', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bandalias',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('alias', 'B', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='basebrochure',
            name='_base_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('titel', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('zusammenfassung', 'B', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('anmerkungen', 'A', 'german_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bildreihe',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('name', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='buch',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('titel', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bundesland',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('bland_name', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('code', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='datei',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('titel', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('titel', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('titel', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='geber',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('name', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('genre', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='genrealias',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('alias', 'B', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='herausgeber',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('herausgeber', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('instrument', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('kuerzel', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='kalender',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lagerort',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('_name', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('land_name', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('code', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('magazin_name', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('issn', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='memorabilien',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('titel', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='monat',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('monat', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('abk', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='musiker',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('kuenstler_name', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='musikeralias',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('alias', 'B', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ort',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('_name', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('_name', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plakat',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('titel', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('signatur', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='plattenfirma',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('name', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='schlagwort',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('schlagwort', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='schlagwortalias',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('alias', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='schriftenreihe',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('name', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='spielort',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('name', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='spielortalias',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('alias', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='technik',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('titel', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('name', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('datum', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='veranstaltungalias',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('alias', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='veranstaltungsreihe',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('name', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='verlag',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('verlag_name', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('titel', 'A', 'simple_unaccent'), dbentry.fts.fields.WeightedColumn('beschreibung', 'C', 'german_unaccent'), dbentry.fts.fields.WeightedColumn('bemerkungen', 'D', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='videomedium',
            name='_fts',
            field=dbentry.fts.fields.SearchVectorField(blank=True, columns=[dbentry.fts.fields.WeightedColumn('medium', 'A', 'simple_unaccent')], editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='artikel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_art__fts_942851_gin'),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_aud__fts_eb00b4_gin'),
        ),
        migrations.AddIndex(
            model_name='audiomedium',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_aud__fts_8ba8a1_gin'),
        ),
        migrations.AddIndex(
            model_name='ausgabe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_aus__fts_317954_gin'),
        ),
        migrations.AddIndex(
            model_name='autor',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_aut__fts_9e30aa_gin'),
        ),
        migrations.AddIndex(
            model_name='band',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_ban__fts_68a1eb_gin'),
        ),
        migrations.AddIndex(
            model_name='bandalias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_ban__fts_84a5c9_gin'),
        ),
        migrations.AddIndex(
            model_name='basebrochure',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_base_fts'], name='dbentry_bas__base_f_a2e3c0_gin'),
        ),
        migrations.AddIndex(
            model_name='bestand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_bes__fts_d8c7d4_gin'),
        ),
        migrations.AddIndex(
            model_name='bildreihe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_bil__fts_46db8e_gin'),
        ),
        migrations.AddIndex(
            model_name='brochure',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_bro__fts_1382a9_gin'),
        ),
        migrations.AddIndex(
            model_name='buch',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_buc__fts_d9ced2_gin'),
        ),
        migrations.AddIndex(
            model_name='bundesland',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_bun__fts_e9ab3e_gin'),
        ),
        migrations.AddIndex(
            model_name='datei',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_dat__fts_98184c_gin'),
        ),
        migrations.AddIndex(
            model_name='dokument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_dok__fts_3ee469_gin'),
        ),
        migrations.AddIndex(
            model_name='foto',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_fot__fts_8ad7d4_gin'),
        ),
        migrations.AddIndex(
            model_name='geber',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_geb__fts_46a121_gin'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_gen__fts_d4ca02_gin'),
        ),
        migrations.AddIndex(
            model_name='genrealias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_gen__fts_da69eb_gin'),
        ),
        migrations.AddIndex(
            model_name='herausgeber',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_her__fts_f41065_gin'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_ins__fts_eda689_gin'),
        ),
        migrations.AddIndex(
            model_name='kalender',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_kal__fts_de8b54_gin'),
        ),
        migrations.AddIndex(
            model_name='katalog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_kat__fts_6f88c8_gin'),
        ),
        migrations.AddIndex(
            model_name='lagerort',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_lag__fts_8d2267_gin'),
        ),
        migrations.AddIndex(
            model_name='land',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_lan__fts_d2ff6a_gin'),
        ),
        migrations.AddIndex(
            model_name='magazin',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_mag__fts_14e698_gin'),
        ),
        migrations.AddIndex(
            model_name='memorabilien',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_mem__fts_2faba8_gin'),
        ),
        migrations.AddIndex(
            model_name='monat',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_mon__fts_1a5157_gin'),
        ),
        migrations.AddIndex(
            model_name='musiker',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_mus__fts_6e1786_gin'),
        ),
        migrations.AddIndex(
            model_name='musikeralias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_mus__fts_425415_gin'),
        ),
        migrations.AddIndex(
            model_name='ort',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_ort__fts_9f5efd_gin'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_per__fts_0a475d_gin'),
        ),
        migrations.AddIndex(
            model_name='plakat',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_pla__fts_7aa8c1_gin'),
        ),
        migrations.AddIndex(
            model_name='plattenfirma',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_pla__fts_43474e_gin'),
        ),
        migrations.AddIndex(
            model_name='schlagwort',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_sch__fts_2a13b7_gin'),
        ),
        migrations.AddIndex(
            model_name='schlagwortalias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_sch__fts_b5bc82_gin'),
        ),
        migrations.AddIndex(
            model_name='schriftenreihe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_sch__fts_572aa2_gin'),
        ),
        migrations.AddIndex(
            model_name='spielort',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_spi__fts_e1d489_gin'),
        ),
        migrations.AddIndex(
            model_name='spielortalias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_spi__fts_60770f_gin'),
        ),
        migrations.AddIndex(
            model_name='technik',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_tec__fts_b08694_gin'),
        ),
        migrations.AddIndex(
            model_name='veranstaltung',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_ver__fts_7c2b53_gin'),
        ),
        migrations.AddIndex(
            model_name='veranstaltungalias',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_ver__fts_f987ab_gin'),
        ),
        migrations.AddIndex(
            model_name='veranstaltungsreihe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_ver__fts_279159_gin'),
        ),
        migrations.AddIndex(
            model_name='verlag',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_ver__fts_d63c51_gin'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_vid__fts_b05921_gin'),
        ),
        migrations.AddIndex(
            model_name='videomedium',
            index=django.contrib.postgres.indexes.GinIndex(fields=['_fts'], name='dbentry_vid__fts_cbed40_gin'),
        ),
        IndexSearchVector('artikel', '_fts'),
        IndexSearchVector('audio', '_fts'),
        IndexSearchVector('audiomedium', '_fts'),
        IndexSearchVector('ausgabe', '_fts'),
        IndexSearchVector('autor', '_fts'),
        IndexSearchVector('band', '_fts'),
        IndexSearchVector('bandalias', '_fts'),
        IndexSearchVector('bestand', '_fts'),
        IndexSearchVector('bildreihe', '_fts'),
        IndexSearchVector('buch', '_fts'),
        IndexSearchVector('bundesland', '_fts'),
        IndexSearchVector('datei', '_fts'),
        IndexSearchVector('dokument', '_fts'),
        IndexSearchVector('foto', '_fts'),
        IndexSearchVector('geber', '_fts'),
        IndexSearchVector('genre', '_fts'),
        IndexSearchVector('genrealias', '_fts'),
        IndexSearchVector('herausgeber', '_fts'),
        IndexSearchVector('instrument', '_fts'),
        IndexSearchVector('lagerort', '_fts'),
        IndexSearchVector('land', '_fts'),
        IndexSearchVector('magazin', '_fts'),
        IndexSearchVector('memorabilien', '_fts'),
        IndexSearchVector('monat', '_fts'),
        IndexSearchVector('musiker', '_fts'),
        IndexSearchVector('musikeralias', '_fts'),
        IndexSearchVector('ort', '_fts'),
        IndexSearchVector('person', '_fts'),
        IndexSearchVector('plakat', '_fts'),
        IndexSearchVector('plattenfirma', '_fts'),
        IndexSearchVector('schlagwort', '_fts'),
        IndexSearchVector('schlagwortalias', '_fts'),
        IndexSearchVector('schriftenreihe', '_fts'),
        IndexSearchVector('spielort', '_fts'),
        IndexSearchVector('spielortalias', '_fts'),
        IndexSearchVector('technik', '_fts'),
        IndexSearchVector('veranstaltung', '_fts'),
        IndexSearchVector('veranstaltungalias', '_fts'),
        IndexSearchVector('veranstaltungsreihe', '_fts'),
        IndexSearchVector('verlag', '_fts'),
        IndexSearchVector('video', '_fts'),
        IndexSearchVector('videomedium', '_fts'),
        IndexSearchVector('basebrochure', '_base_fts'),
        IndexSearchVector('brochure', '_fts'),
        IndexSearchVector('kalender', '_fts'),
        IndexSearchVector('katalog', '_fts'),
    ]
