# Generated by Django 4.2.15 on 2024-08-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbentry", "0031_alter_autorurl_url_alter_bandurl_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ausgabe",
            name="e_datum",
            field=models.DateField(
                blank=True, null=True, verbose_name="Erscheinungsdatum"
            ),
        ),
    ]
