# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0032_magazin_verlag_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazin',
            name='verlag',
        ),
    ]
