# Generated by Django 4.1.7 on 2023-06-07 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dbentry", "0032_alter_printmediatype_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="printmedia",
            name="_brochure_ptr",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dbentry.basebrochure",
            ),
        ),
    ]
