# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0033_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestand',
            name='typ',
            field=models.CharField(choices=[('Schenkung', 'Schenkung'), ('Spender', 'Spende'), ('Fund', 'Fund'), ('Leihgabe', 'Leihgabe'), ('Dauerleihgabe', 'Dauerleihgabe')], default='Schenkung', max_length=100, verbose_name='Art der Provenienz'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='provenienz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.geber'),
        ),
    ]
