# Generated by Django 4.1.7 on 2023-06-07 09:40

import dbentry.fts.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbentry", "0033_printmedia__brochure_ptr"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printmediatype",
            options={
                "ordering": ["typ"],
                "verbose_name": "Druckerzeugnistyp",
                "verbose_name_plural": "Druckerzeugnistypen",
            },
        ),
        migrations.AddField(
            model_name="printmediatype",
            name="_fts",
            field=dbentry.fts.fields.SearchVectorField(
                columns=[
                    dbentry.fts.fields.WeightedColumn("typ", "A", "simple_unaccent")
                ]
            ),
        ),
        migrations.AlterField(
            model_name="printmediatype",
            name="typ",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
