# Generated by Django 4.2.21 on 2025-07-30 08:43

import dbentry.fts.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dbentry", "0034_alter_abstract_url_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoTyp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Typ"),
                ),
                (
                    "_fts",
                    dbentry.fts.fields.SearchVectorField(
                        columns=[
                            dbentry.fts.fields.WeightedColumn(
                                "name", "A", "simple_unaccent"
                            )
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "Memorabilie-Typ",
                "verbose_name_plural": "Memorabilie-Typen",
                "ordering": ["name"],
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "merge", "view"),
            },
        ),
        migrations.AlterModelOptions(
            name="memorabilien",
            options={
                "default_permissions": ("add", "change", "delete", "merge", "view"),
                "ordering": ["titel"],
                "verbose_name": "Memorabilie",
                "verbose_name_plural": "Memorabilien",
            },
        ),
        migrations.AlterField(
            model_name="memorabilien",
            name="beschreibung",
            field=models.TextField(
                blank=True, help_text="Beschreibung der Memorabilie"
            ),
        ),
        migrations.AddField(
            model_name="memorabilien",
            name="typ",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dbentry.memotyp",
                verbose_name="Art d. Memorabilie",
            ),
        ),
    ]
