# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0034_DBentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestand',
            old_name='provenienz',
            new_name='geber',
        ),
    ]
