# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0035_alter_magazin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='laufzeit',
            field=models.DurationField(blank=True, help_text='Format: hh:mm:ss', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='laufzeit',
            field=models.DurationField(blank=True, help_text='Format: hh:mm:ss', null=True),
        ),
    ]
