# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0035_DBentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestand',
            options={'verbose_name': 'Bestand', 'verbose_name_plural': 'Bestände'},
        ),
        migrations.AlterField(
            model_name='bestand',
            name='ausgabe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.ausgabe'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='buch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.buch'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='geber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.geber'),
        ),
    ]
