# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0037_DBentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestand',
            name='geber',
        ),
        migrations.RemoveField(
            model_name='bestand',
            name='typ',
        ),
        migrations.AddField(
            model_name='bestand',
            name='provenienz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.provenienz'),
        ),
    ]
