# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 13:41
from __future__ import unicode_literals

import DBentry.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0037_alter_field_verlag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBrochure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('zusammenfassung', models.TextField(blank=True)),
                ('bemerkungen', models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter')),
            ],
            options={
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='BrochureYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', DBentry.fields.YearField(verbose_name='Jahr')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Jahre',
                'ordering': ['jahr'],
                'verbose_name': 'Jahr',
                'default_permissions': ('add', 'change', 'delete', 'merge'),
            },
        ),
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('basebrochure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DBentry.BaseBrochure')),
                ('beschreibung', models.TextField(blank=True, help_text='Beschreibung bzgl. der Broschüre')),
                ('schlagwort', models.ManyToManyField(to='DBentry.schlagwort')),
            ],
            options={
                'verbose_name_plural': 'Broschüren',
                'verbose_name': 'Broschüre',
            },
            bases=('DBentry.basebrochure',),
        ),
        migrations.CreateModel(
            name='Kalendar',
            fields=[
                ('basebrochure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DBentry.BaseBrochure')),
                ('beschreibung', models.TextField(blank=True, help_text='Beschreibung bzgl. des Programmheftes')),
                ('spielort', models.ManyToManyField(to='DBentry.spielort')),
                ('veranstaltung', models.ManyToManyField(to='DBentry.veranstaltung')),
            ],
            options={
                'verbose_name_plural': 'Programmhefte',
                'verbose_name': 'Programmheft',
            },
            bases=('DBentry.basebrochure',),
        ),
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('basebrochure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DBentry.BaseBrochure')),
                ('beschreibung', models.TextField(blank=True, help_text='Beschreibung bzgl. des Kataloges')),
                ('art', models.CharField(choices=[('merch', 'Merchandise'), ('tech', 'Technik'), ('ton', 'Tonträger')], default=1, max_length=40, verbose_name='Art d. Kataloges')),
            ],
            options={
                'verbose_name_plural': 'Warenkataloge',
                'verbose_name': 'Warenkatalog',
            },
            bases=('DBentry.basebrochure',),
        ),
        migrations.AddField(
            model_name='brochureyear',
            name='brochure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jahre', to='DBentry.BaseBrochure'),
        ),
        migrations.AddField(
            model_name='basebrochure',
            name='ausgabe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beilagen', to='DBentry.ausgabe', verbose_name='Ausgabe'),
        ),
        migrations.AddField(
            model_name='basebrochure',
            name='genre',
            field=models.ManyToManyField(to='DBentry.genre'),
        ),
        migrations.AddField(
            model_name='bestand',
            name='brochure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.BaseBrochure'),
        ),
    ]
