# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0038_DBentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestand',
            name='id',
        ),
        migrations.AddField(
            model_name='bestand',
            name='signatur',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
