# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0039_add_brochure_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basebrochure',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['titel']},
        ),
        migrations.AlterModelOptions(
            name='brochure',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'verbose_name': 'Broschüre', 'verbose_name_plural': 'Broschüren'},
        ),
        migrations.AlterModelOptions(
            name='kalendar',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'verbose_name': 'Programmheft', 'verbose_name_plural': 'Programmhefte'},
        ),
        migrations.AlterModelOptions(
            name='katalog',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'verbose_name': 'Warenkatalog', 'verbose_name_plural': 'Warenkataloge'},
        ),
    ]
