# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0039_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestand',
            name='lagerort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DBentry.lagerort'),
            preserve_default=False,
        ),
    ]
