# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 13:24
from __future__ import unicode_literals

import DBentry.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0040_add_basemodel_perms_to_brochure_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='e_jahr',
            field=DBentry.fields.YearField(blank=True, null=True, verbose_name='Erscheinungsjahr'),
        ),
        migrations.AlterField(
            model_name='ausgabe_jahr',
            name='jahr',
            field=DBentry.fields.YearField(verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='jahr',
            field=DBentry.fields.YearField(blank=True, null=True, verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='jahr_orig',
            field=DBentry.fields.YearField(blank=True, null=True, verbose_name='Jahr (Original)'),
        ),
    ]
