# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0041_adds_yearfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='discogs_url',
            field=models.URLField(blank=True, default='', verbose_name='Link discogs.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brochureurl',
            name='brochure',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='DBentry.BaseBrochure'),
            preserve_default=False,
        ),
    ]
