# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0041_DBentryMaxL200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lagerort',
            old_name='name',
            new_name='ort',
        ),
        migrations.AddField(
            model_name='lagerort',
            name='raum',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lagerort',
            name='regal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
