# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0042_DBentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
