# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0042_removes_urlfield_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazin',
            name='verlag',
            field=models.ManyToManyField(through='DBentry.m2m_magazin_verlag', to='DBentry.verlag'),
        ),
    ]
