# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0043_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestand',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.audio'),
        ),
        migrations.AddField(
            model_name='bestand',
            name='bildmaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.bildmaterial'),
        ),
        migrations.AddField(
            model_name='bestand',
            name='dokument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.dokument'),
        ),
        migrations.AddField(
            model_name='bestand',
            name='memorabilien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.memorabilien'),
        ),
        migrations.AddField(
            model_name='bestand',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.video'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.sender'),
        ),
    ]
