# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0044_katalog_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazin',
            name='herausgeber',
            field=models.ManyToManyField(through='DBentry.m2m_magazin_herausgeber', to='DBentry.Herausgeber'),
        ),
    ]
