# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0044_DBentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='lagerort',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lagerort',
        ),
    ]
