# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0045_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestand',
            name='technik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.technik'),
        ),
    ]
