# Generated by Django 2.2 on 2019-04-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0045_adds_explicit_magazin_herausgeber_m2m_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buch',
            name='buchband',
            field=models.ForeignKey(blank=True, help_text='Der Sammelband, der diesen Aufsatz enthält.', limit_choices_to={'is_buchband': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buch_set', to='DBentry.buch', verbose_name='Sammelband'),
        ),
    ]
