# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0046_DBentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geber',
            options={},
        ),
        migrations.RemoveField(
            model_name='person',
            name='original_id',
        ),
    ]
