# Generated by Django 2.2 on 2019-05-27 07:00

import DBentry.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0047_removed_alter_data_ausgabe_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildmaterial',
            name='datum',
            field=DBentry.fields.PartialDateField(blank=True, max_length=10),
        ),
    ]
