# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0047_DBentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgabe',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.magazin', verbose_name='Magazin'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.person'),
        ),
        migrations.AlterField(
            model_name='band',
            name='herkunft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='bundesland',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.land', verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='ober',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obergenre', to='DBentry.genre', verbose_name='Oberbegriff'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='magazin_url',
            field=models.URLField(blank=True, verbose_name='Webpage'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='ort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.ort', verbose_name='Hrsg.Ort'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='verlag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DBentry.verlag'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='bland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DBentry.bundesland', verbose_name='Bundesland'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.land', verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='person',
            name='herkunft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='verlag',
            name='sitz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.ort'),
        ),
    ]
