# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0048_DBentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veranstaltung',
            old_name='bands',
            new_name='band',
        ),
    ]
