# Generated by Django 2.2 on 2019-06-03 10:27

import DBentry.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0049_add_bildmaterial_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='datum',
            field=DBentry.fields.PartialDateField(blank=True, max_length=10),
        ),
    ]
