# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0050_DBentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='mitglieder',
            new_name='musiker',
        ),
    ]
