# Generated by Django 2.2 on 2019-06-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0050_alter_veranstaltung_datum_to_partial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veranstaltung',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['name', 'datum', 'spielort'], 'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
    ]
