# Generated by Django 2.2 on 2019-06-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0051_veranstaltung_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildreihe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'merge'),
                'verbose_name_plural': 'Bildreihen',
                'abstract': False,
                'ordering': ['name'],
                'verbose_name': 'Bildreihe',
            },
        ),
    ]
