# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0051_DBentry'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
        migrations.CreateModel(
            name='m2m_artikel_autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_artikel_autor',
            },
        ),
        migrations.CreateModel(
            name='m2m_artikel_band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_artikel_band',
            },
        ),
        migrations.CreateModel(
            name='m2m_artikel_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_artikel_genre',
            },
        ),
        migrations.CreateModel(
            name='m2m_artikel_musiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_artikel_musiker',
            },
        ),
        migrations.CreateModel(
            name='m2m_artikel_ort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_artikel_ort',
            },
        ),
        migrations.CreateModel(
            name='m2m_artikel_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_artikel_person',
            },
        ),
        migrations.CreateModel(
            name='m2m_artikel_schlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_artikel_schlagwort',
            },
        ),
        migrations.CreateModel(
            name='m2m_artikel_spielort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_artikel_spielort',
            },
        ),
        migrations.CreateModel(
            name='m2m_artikel_veranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_artikel_veranstaltung',
            },
        ),
        migrations.CreateModel(
            name='m2m_autor_magazin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_autor_magazin',
            },
        ),
        migrations.CreateModel(
            name='m2m_band_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_band_genre',
            },
        ),
        migrations.CreateModel(
            name='m2m_band_musiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_band_musiker',
            },
        ),
        migrations.CreateModel(
            name='m2m_buch_autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_buch_autor',
            },
        ),
        migrations.CreateModel(
            name='m2m_magazin_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
            ],
            options={
                'db_table': 'DBentry_magazin_genre',
            },
        ),
        migrations.CreateModel(
            name='m2m_musiker_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
            ],
            options={
                'db_table': 'DBentry_musiker_genre',
            },
        ),
        migrations.CreateModel(
            name='m2m_musiker_instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.instrument')),
            ],
            options={
                'db_table': 'DBentry_musiker_instrument',
            },
        ),
        migrations.CreateModel(
            name='m2m_veranstaltung_band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DBentry_veranstaltung_band',
            },
        ),
        migrations.CreateModel(
            name='m2m_veranstaltung_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
            ],
            options={
                'db_table': 'DBentry_veranstaltung_genre',
            },
        ),
        migrations.CreateModel(
            name='m2m_veranstaltung_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.person')),
            ],
            options={
                'db_table': 'DBentry_veranstaltung_person',
            },
        ),
        migrations.AlterField(
            model_name='artikel',
            name='autor',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_autor', to='DBentry.autor'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='band',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_band', to='DBentry.band'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='musiker',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_musiker', to='DBentry.musiker'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='ort',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_ort', to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='person',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_person', to='DBentry.person'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='schlagwort',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_schlagwort', to='DBentry.schlagwort'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='spielort',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_spielort', to='DBentry.spielort'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='veranstaltung',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_veranstaltung', to='DBentry.veranstaltung'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='magazin',
            field=models.ManyToManyField(blank=True, through='DBentry.m2m_autor_magazin', to='DBentry.magazin'),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_band_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='band',
            name='musiker',
            field=models.ManyToManyField(through='DBentry.m2m_band_musiker', to='DBentry.musiker'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='autor',
            field=models.ManyToManyField(through='DBentry.m2m_buch_autor', to='DBentry.autor'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='genre',
            field=models.ManyToManyField(blank=True, through='DBentry.m2m_magazin_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='musiker',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_musiker_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='musiker',
            name='instrument',
            field=models.ManyToManyField(through='DBentry.m2m_musiker_instrument', to='DBentry.instrument'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='band',
            field=models.ManyToManyField(through='DBentry.m2m_veranstaltung_band', to='DBentry.band', verbose_name='Teilnehmer (Bands)'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_veranstaltung_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='person',
            field=models.ManyToManyField(through='DBentry.m2m_veranstaltung_person', to='DBentry.person', verbose_name='Teilnehmer (Personen)'),
        ),
        migrations.AddField(
            model_name='m2m_veranstaltung_person',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung'),
        ),
        migrations.AddField(
            model_name='m2m_veranstaltung_genre',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung'),
        ),
        migrations.AddField(
            model_name='m2m_veranstaltung_band',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band'),
        ),
        migrations.AddField(
            model_name='m2m_veranstaltung_band',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung'),
        ),
        migrations.AddField(
            model_name='m2m_musiker_instrument',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker'),
        ),
        migrations.AddField(
            model_name='m2m_musiker_genre',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker'),
        ),
        migrations.AddField(
            model_name='m2m_magazin_genre',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.magazin'),
        ),
        migrations.AddField(
            model_name='m2m_buch_autor',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.autor'),
        ),
        migrations.AddField(
            model_name='m2m_buch_autor',
            name='buch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.buch'),
        ),
        migrations.AddField(
            model_name='m2m_band_musiker',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band'),
        ),
        migrations.AddField(
            model_name='m2m_band_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker'),
        ),
        migrations.AddField(
            model_name='m2m_band_genre',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band'),
        ),
        migrations.AddField(
            model_name='m2m_band_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre'),
        ),
        migrations.AddField(
            model_name='m2m_autor_magazin',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.autor'),
        ),
        migrations.AddField(
            model_name='m2m_autor_magazin',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.magazin'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_veranstaltung',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_veranstaltung',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_spielort',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_spielort',
            name='spielort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.spielort'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_schlagwort',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_schlagwort',
            name='schlagwort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.schlagwort'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_person',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_person',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.person'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_ort',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_ort',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.ort'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_musiker',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_genre',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_band',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_band',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_autor',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel'),
        ),
        migrations.AddField(
            model_name='m2m_artikel_autor',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.autor'),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_veranstaltung_person',
            unique_together=set([('veranstaltung', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_veranstaltung_genre',
            unique_together=set([('veranstaltung', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_veranstaltung_band',
            unique_together=set([('veranstaltung', 'band')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_musiker_instrument',
            unique_together=set([('musiker', 'instrument')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_musiker_genre',
            unique_together=set([('musiker', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_magazin_genre',
            unique_together=set([('magazin', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_buch_autor',
            unique_together=set([('buch', 'autor')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_band_musiker',
            unique_together=set([('band', 'musiker')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_band_genre',
            unique_together=set([('band', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_autor_magazin',
            unique_together=set([('autor', 'magazin')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_veranstaltung',
            unique_together=set([('artikel', 'veranstaltung')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_spielort',
            unique_together=set([('artikel', 'spielort')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_schlagwort',
            unique_together=set([('artikel', 'schlagwort')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_person',
            unique_together=set([('artikel', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_ort',
            unique_together=set([('artikel', 'ort')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_musiker',
            unique_together=set([('artikel', 'musiker')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_genre',
            unique_together=set([('artikel', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_band',
            unique_together=set([('artikel', 'band')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_autor',
            unique_together=set([('artikel', 'autor')]),
        ),
    ])]
