# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0052_DBentry_ALTER_throughs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m2m_band_genre',
            options={'verbose_name': 'Band-Genre', 'verbose_name_plural': 'Band-Genres'},
        ),
        migrations.AlterField(
            model_name='m2m_artikel_band',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.band'),
        ),
        migrations.AlterField(
            model_name='m2m_band_genre',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.band'),
        ),
        migrations.AlterField(
            model_name='m2m_band_musiker',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.band'),
        ),
    ]
