# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0053_DBentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m2m_artikel_autor',
            options={'verbose_name': 'Artikel-Autor', 'verbose_name_plural': 'Artikel-Autoren'},
        ),
        migrations.AlterModelOptions(
            name='m2m_artikel_band',
            options={'verbose_name': 'Artikel-Band', 'verbose_name_plural': 'Artikel-Bands'},
        ),
        migrations.AlterModelOptions(
            name='m2m_artikel_genre',
            options={'verbose_name': 'Artikel-Genre', 'verbose_name_plural': 'Artikel-Genres'},
        ),
        migrations.AlterModelOptions(
            name='m2m_artikel_musiker',
            options={'verbose_name': 'Artikel-Musiker', 'verbose_name_plural': 'Artikel-Musiker'},
        ),
        migrations.AlterModelOptions(
            name='m2m_artikel_ort',
            options={'verbose_name': 'Artikel-Ort', 'verbose_name_plural': 'Artikel-Orte'},
        ),
        migrations.AlterModelOptions(
            name='m2m_artikel_person',
            options={'verbose_name': 'Artikel-Person', 'verbose_name_plural': 'Artikel-Personen'},
        ),
        migrations.AlterModelOptions(
            name='m2m_artikel_schlagwort',
            options={'verbose_name': 'Artikel-Schlagwort', 'verbose_name_plural': 'Artikel-Schlagwörter'},
        ),
        migrations.AlterModelOptions(
            name='m2m_artikel_spielort',
            options={'verbose_name': 'Artikel-Spielort', 'verbose_name_plural': 'Artikel-Spielorte'},
        ),
        migrations.AlterModelOptions(
            name='m2m_artikel_veranstaltung',
            options={'verbose_name': 'Artikel-Veranstaltung', 'verbose_name_plural': 'Artikel-Veranstaltungen'},
        ),
        migrations.AlterModelOptions(
            name='m2m_autor_magazin',
            options={'verbose_name': 'Autor-Magazin', 'verbose_name_plural': 'Autor-Magazine'},
        ),
        migrations.AlterModelOptions(
            name='m2m_band_musiker',
            options={'verbose_name': 'Band-Mitglied', 'verbose_name_plural': 'Band-Mitglieder'},
        ),
        migrations.AlterModelOptions(
            name='m2m_buch_autor',
            options={'verbose_name': 'Buch-Autor', 'verbose_name_plural': 'Buch-Autoren'},
        ),
        migrations.AlterModelOptions(
            name='m2m_magazin_genre',
            options={'verbose_name': 'Magazin-Genre', 'verbose_name_plural': 'Magazin-Genres'},
        ),
        migrations.AlterModelOptions(
            name='m2m_musiker_genre',
            options={'verbose_name': 'Musiker-Genre', 'verbose_name_plural': 'Musiker-Genres'},
        ),
        migrations.AlterModelOptions(
            name='m2m_musiker_instrument',
            options={'verbose_name': 'Musiker-Instrument', 'verbose_name_plural': 'Musiker-Instrumente'},
        ),
        migrations.AlterModelOptions(
            name='m2m_veranstaltung_band',
            options={'verbose_name': 'Veranstaltung-Band', 'verbose_name_plural': 'Veranstaltung-Bands'},
        ),
        migrations.AlterModelOptions(
            name='m2m_veranstaltung_genre',
            options={'verbose_name': 'Veranstaltung-Genre', 'verbose_name_plural': 'Veranstaltung-Genres'},
        ),
        migrations.AlterModelOptions(
            name='m2m_veranstaltung_person',
            options={'verbose_name': 'Veranstaltung-Person', 'verbose_name_plural': 'Veranstaltung-Personen'},
        ),
    ]
