# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0054_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausgabe',
            name='sonderausgabe',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='magazin',
            name='ausgaben_merkmal',
            field=models.CharField(blank=True, choices=[('num', 'Nummer'), ('lnum', 'Lfd.Nummer'), ('monat', 'Monat')], max_length=200),
        ),
        migrations.AlterField(
            model_name='m2m_autor_magazin',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.magazin'),
        ),
    ]
