# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0055_DBentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausgabe',
            name='sonderausgabe',
        ),
    ]
