# Generated by Django 2.2 on 2019-06-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0055_add_veranstaltung_reihe'),
    ]

    operations = [
        migrations.AddField(
            model_name='veranstaltung',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='veranstaltung',
            name='beschreibung',
            field=models.TextField(blank=True),
        ),
    ]
