# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0056_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausgabe',
            name='sonderausgabe',
            field=models.BooleanField(default=False),
        ),
    ]
