# Generated by Django 2.2 on 2019-06-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0056_add_veranstaltung_beschreibung_bemerkungen'),
    ]

    operations = [
        migrations.AddField(
            model_name='spielort',
            name='bemerkungen',
            field=models.TextField(blank=True, help_text='Kommentare für Archiv-Mitarbeiter'),
        ),
        migrations.AddField(
            model_name='spielort',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. des Spielortes'),
        ),
    ]
