# Generated by Django 2.2 on 2019-06-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0057_add_spielort_beschreibung_bemerkungen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildmaterial',
            name='signatur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
