# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0058_DBentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausgabe',
            name='jahrgang',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
