# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 13:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0059_DBentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausgabe',
            options={'ordering': ['magazin'], 'verbose_name': 'Ausgabe', 'verbose_name_plural': 'Ausgaben'},
        ),
        migrations.AlterModelOptions(
            name='lagerort',
            options={'ordering': ['ort'], 'verbose_name': 'Lagerort', 'verbose_name_plural': 'Lagerorte'},
        ),
        migrations.AlterModelOptions(
            name='provenienz',
            options={'verbose_name': 'Provenienz', 'verbose_name_plural': 'Provenienzen'},
        ),
        migrations.AlterField(
            model_name='ausgabe_jahr',
            name='jahr',
            field=models.IntegerField(default=2017, validators=[django.core.validators.MaxValueValidator(2017), django.core.validators.MinValueValidator(1899)], verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='ausgaben_merkmal',
            field=models.CharField(blank=True, choices=[('num', 'Nummer'), ('lnum', 'Lfd.Nummer'), ('monat', 'Monat'), ('e_datum', 'Ersch.Datum')], max_length=200),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='turnus',
            field=models.CharField(blank=True, choices=[('u', 'unbekannt'), ('t', 'täglich'), ('w', 'wöchentlich'), ('w2', 'zwei-wöchentlich'), ('m', 'monatlich'), ('m2', 'zwei-monatlich'), ('q', 'quartalsweise'), ('hj', 'halbjährlich'), ('j', 'jährlich')], default='u', max_length=200),
        ),
        migrations.AlterField(
            model_name='provenienz',
            name='typ',
            field=models.CharField(choices=[('Schenkung', 'Schenkung'), ('Spende', 'Spende'), ('Fund', 'Fund'), ('Leihgabe', 'Leihgabe'), ('Dauerleihgabe', 'Dauerleihgabe')], default='Schenkung', max_length=100, verbose_name='Art der Provenienz'),
        ),
    ]
