# Generated by Django 2.2 on 2019-10-21 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0059_bildmaterial_signatur_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.person'),
        ),
    ]
