# Generated by Django 2.2 on 2019-10-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0060_alter_autor_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgabe',
            name='status',
            field=models.CharField(choices=[('unb', 'unbearbeitet'), ('iB', 'in Bearbeitung'), ('abg', 'abgeschlossen'), ('kB', 'keine Bearbeitung vorgesehen')], default='unb', max_length=40, verbose_name='Bearbeitungsstatus'),
        ),
    ]
