# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 13:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0060_DBentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgabe_jahr',
            name='jahr',
            field=models.PositiveSmallIntegerField(default=2017, validators=[django.core.validators.MaxValueValidator(2017), django.core.validators.MinValueValidator(1899)], verbose_name='Jahr'),
        ),
    ]
