# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0061_DBentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='m2m_audio_band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.audio')),
            ],
            options={
                'verbose_name_plural': 'Audio-Bands',
                'db_table': 'DBentry_audio_band',
                'verbose_name': 'Audio-Band',
            },
        ),
        migrations.CreateModel(
            name='m2m_audio_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.audio')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
            ],
            options={
                'verbose_name_plural': 'Audio-Genres',
                'db_table': 'DBentry_audio_genre',
                'verbose_name': 'Audio-Genre',
            },
        ),
        migrations.CreateModel(
            name='m2m_audio_musiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.audio')),
                ('musiker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker')),
            ],
            options={
                'verbose_name_plural': 'Audio-Musiker',
                'db_table': 'DBentry_audio_musiker',
                'verbose_name': 'Audio-Musiker',
            },
        ),
        migrations.CreateModel(
            name='m2m_audio_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.audio')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.person')),
            ],
            options={
                'verbose_name_plural': 'Audio-Personen',
                'db_table': 'DBentry_audio_person',
                'verbose_name': 'Audio-Person',
            },
        ),
        migrations.CreateModel(
            name='m2m_audio_schlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.audio')),
                ('schlagwort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.schlagwort')),
            ],
            options={
                'verbose_name_plural': 'Audio-Schlagworte',
                'db_table': 'DBentry_audio_schlagwort',
                'verbose_name': 'Audio-Schlagwort',
            },
        ),
        migrations.CreateModel(
            name='m2m_audio_spielort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.audio')),
                ('spielort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.spielort')),
            ],
            options={
                'verbose_name_plural': 'Audio-Spielorte',
                'db_table': 'DBentry_audio_spielort',
                'verbose_name': 'Audio-Spielort',
            },
        ),
        migrations.CreateModel(
            name='m2m_audio_veranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.audio')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung')),
            ],
            options={
                'verbose_name_plural': 'Audio-Veranstaltungen',
                'db_table': 'DBentry_audio_veranstaltung',
                'verbose_name': 'Audio-Veranstaltung',
            },
        ),
        migrations.CreateModel(
            name='m2m_video_band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Video-Bands',
                'db_table': 'DBentry_video_band',
                'verbose_name': 'Video-Band',
            },
        ),
        migrations.CreateModel(
            name='m2m_video_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.video')),
            ],
            options={
                'verbose_name_plural': 'Video-Genres',
                'db_table': 'DBentry_video_genre',
                'verbose_name': 'Video-Genre',
            },
        ),
        migrations.CreateModel(
            name='m2m_video_musiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musiker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.video')),
            ],
            options={
                'verbose_name_plural': 'Video-Musiker',
                'db_table': 'DBentry_video_musiker',
                'verbose_name': 'Video-Musiker',
            },
        ),
        migrations.CreateModel(
            name='m2m_video_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.person')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.video')),
            ],
            options={
                'verbose_name_plural': 'Video-Personen',
                'db_table': 'DBentry_video_person',
                'verbose_name': 'Video-Person',
            },
        ),
        migrations.CreateModel(
            name='m2m_video_schlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schlagwort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.schlagwort')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.video')),
            ],
            options={
                'verbose_name_plural': 'Video-Schlagwörter',
                'db_table': 'DBentry_video_schlagwort',
                'verbose_name': 'Video-Schlagwort',
            },
        ),
        migrations.CreateModel(
            name='m2m_video_spielort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spielort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.spielort')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.video')),
            ],
            options={
                'verbose_name_plural': 'Video-Spielorte',
                'db_table': 'DBentry_video_spielort',
                'verbose_name': 'Video-Spielort',
            },
        ),
        migrations.CreateModel(
            name='m2m_video_veranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.video')),
            ],
            options={
                'verbose_name_plural': 'Video-Veranstaltungen',
                'db_table': 'DBentry_video_veranstaltung',
                'verbose_name': 'Video-Veranstaltung',
            },
        ),
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['seite', 'ausgabe', 'pk'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterModelOptions(
            name='ausgabe',
            options={'ordering': ['magazin', 'jahrgang'], 'verbose_name': 'Ausgabe', 'verbose_name_plural': 'Ausgaben'},
        ),
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['band_name'], 'verbose_name': 'Band', 'verbose_name_plural': 'Bands'},
        ),
        migrations.AlterModelOptions(
            name='bestand',
            options={'ordering': ['pk'], 'verbose_name': 'Bestand', 'verbose_name_plural': 'Bestände'},
        ),
        migrations.AlterModelOptions(
            name='geber',
            options={'verbose_name': 'Geber', 'verbose_name_plural': 'Geber'},
        ),
        migrations.AlterModelOptions(
            name='verlag',
            options={'ordering': ['verlag_name', 'sitz'], 'verbose_name': 'Verlag', 'verbose_name_plural': 'Verlage'},
        ),
        migrations.AddField(
            model_name='bestand',
            name='bestand_art',
            field=models.CharField(choices=[('audio', 'Audio'), ('ausgabe', 'Ausgabe'), ('bildmaterial', 'Bildmaterial'), ('buch', 'Buch'), ('dokument', 'Dokument'), ('memorabilien', 'Memorabilien'), ('technik', 'Technik'), ('video', 'Video')], default='ausgabe', max_length=20, verbose_name='Bestand-Art'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_genre', to='DBentry.genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='schlagwort',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_schlagwort', to='DBentry.schlagwort', verbose_name='Schlagwort'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='seite',
            field=models.PositiveSmallIntegerField(verbose_name='Seite'),
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='jahrgang',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jahrgang'),
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='sonderausgabe',
            field=models.BooleanField(default=False, verbose_name='Sonderausgabe'),
        ),
        migrations.AddField(
            model_name='m2m_video_band',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band'),
        ),
        migrations.AddField(
            model_name='m2m_video_band',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.video'),
        ),
        migrations.AddField(
            model_name='m2m_audio_band',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band'),
        ),
        migrations.AddField(
            model_name='audio',
            name='band',
            field=models.ManyToManyField(through='DBentry.m2m_audio_band', to='DBentry.band'),
        ),
        migrations.AddField(
            model_name='audio',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_audio_genre', to='DBentry.genre'),
        ),
        migrations.AddField(
            model_name='audio',
            name='musiker',
            field=models.ManyToManyField(through='DBentry.m2m_audio_musiker', to='DBentry.musiker'),
        ),
        migrations.AddField(
            model_name='audio',
            name='person',
            field=models.ManyToManyField(through='DBentry.m2m_audio_person', to='DBentry.person'),
        ),
        migrations.AddField(
            model_name='audio',
            name='schlagwort',
            field=models.ManyToManyField(through='DBentry.m2m_audio_schlagwort', to='DBentry.schlagwort'),
        ),
        migrations.AddField(
            model_name='audio',
            name='spielort',
            field=models.ManyToManyField(through='DBentry.m2m_audio_spielort', to='DBentry.spielort'),
        ),
        migrations.AddField(
            model_name='audio',
            name='veranstaltung',
            field=models.ManyToManyField(through='DBentry.m2m_audio_veranstaltung', to='DBentry.veranstaltung'),
        ),
        migrations.AddField(
            model_name='video',
            name='band',
            field=models.ManyToManyField(through='DBentry.m2m_video_band', to='DBentry.band'),
        ),
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_video_genre', to='DBentry.genre'),
        ),
        migrations.AddField(
            model_name='video',
            name='musiker',
            field=models.ManyToManyField(through='DBentry.m2m_video_musiker', to='DBentry.musiker'),
        ),
        migrations.AddField(
            model_name='video',
            name='person',
            field=models.ManyToManyField(through='DBentry.m2m_video_person', to='DBentry.person'),
        ),
        migrations.AddField(
            model_name='video',
            name='schlagwort',
            field=models.ManyToManyField(through='DBentry.m2m_video_schlagwort', to='DBentry.schlagwort'),
        ),
        migrations.AddField(
            model_name='video',
            name='spielort',
            field=models.ManyToManyField(through='DBentry.m2m_video_spielort', to='DBentry.spielort'),
        ),
        migrations.AddField(
            model_name='video',
            name='veranstaltung',
            field=models.ManyToManyField(through='DBentry.m2m_video_veranstaltung', to='DBentry.veranstaltung'),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_video_veranstaltung',
            unique_together=set([('video', 'veranstaltung')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_video_spielort',
            unique_together=set([('video', 'spielort')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_video_schlagwort',
            unique_together=set([('video', 'schlagwort')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_video_person',
            unique_together=set([('video', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_video_musiker',
            unique_together=set([('video', 'musiker')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_video_genre',
            unique_together=set([('video', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_video_band',
            unique_together=set([('video', 'band')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_audio_veranstaltung',
            unique_together=set([('audio', 'veranstaltung')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_audio_spielort',
            unique_together=set([('audio', 'spielort')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_audio_schlagwort',
            unique_together=set([('audio', 'schlagwort')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_audio_person',
            unique_together=set([('audio', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_audio_musiker',
            unique_together=set([('audio', 'musiker')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_audio_genre',
            unique_together=set([('audio', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_audio_band',
            unique_together=set([('audio', 'band')]),
        ),
    ]
