# Generated by Django 2.2 on 2019-10-23 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0062_removed_magazin_erstausgabe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazin',
            name='ort',
            field=models.ForeignKey(blank=True, help_text='Angabe für auf eine Region beschränktes Magazin.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.ort', verbose_name='Herausgabeort'),
        ),
    ]
