# Generated by Django 2.2 on 2019-10-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0063_alter_magazin_ort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buch',
            name='autor',
            field=models.ManyToManyField(to='DBentry.autor'),
        ),
    ]
