# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0064_DBentry_FormatTags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formattag',
            options={'ordering': ['tag'], 'verbose_name': 'Tagss', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='plattenfirma',
            options={'ordering': ['name'], 'verbose_name': 'Plattenfirma', 'verbose_name_plural': 'Plattenfirmen'},
        ),
    ]
