# Generated by Django 2.2 on 2019-10-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0064_alter_buch_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalog',
            name='art',
            field=models.CharField(choices=[('merch', 'Merchandise'), ('tech', 'Instrumente & Technik'), ('ton', 'Tonträger'), ('buch', 'Bücher'), ('other', 'Anderes')], default='merch', max_length=40, verbose_name='Art d. Kataloges'),
        ),
    ]
