# Generated by Django 2.2 on 2019-10-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0065_alter_katalog_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='seitenumfang',
            field=models.CharField(blank=True, choices=[('f', 'f'), ('ff', 'ff')], default='', help_text='Zwei Seiten: f; mehr als zwei Seiten: ff.', max_length=3),
        ),
    ]
