# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0065_DBentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='m2m_audio_ausgabe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.audio')),
            ],
            options={
                'verbose_name_plural': 'Musik-Beilagen',
                'verbose_name': 'Musik-Beilage',
                'db_table': 'DBentry_audio_ausgabe',
            },
        ),
        migrations.AlterModelOptions(
            name='formattag',
            options={'ordering': ['tag'], 'verbose_name': 'Format-Tag', 'verbose_name_plural': 'Format-Tags'},
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='e_datum',
            field=models.DateField(blank=True, help_text='Format: tt.mm.jjjj', null=True, verbose_name='Erscheinungsdatum'),
        ),
        migrations.AddField(
            model_name='m2m_audio_ausgabe',
            name='ausgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ausgabe'),
        ),
        migrations.AddField(
            model_name='ausgabe',
            name='audio',
            field=models.ManyToManyField(through='DBentry.m2m_audio_ausgabe', to='DBentry.audio'),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_audio_ausgabe',
            unique_together=set([('audio', 'ausgabe')]),
        ),
    ]
