# Generated by Django 2.2 on 2019-10-23 10:39

import DBentry.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0066_alter_artikel_seitenumfang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazin',
            name='ausgaben_merkmal',
            field=models.CharField(blank=True, choices=[('num', 'Nummer'), ('lnum', 'Lfd.Nummer'), ('monat', 'Monat'), ('e_datum', 'Ersch.Datum')], help_text='Das dominante Merkmal der Ausgaben. Diese Angabe bestimmt die Darstellung der Ausgaben in der Änderungsliste.', max_length=200, verbose_name='Ausgaben Merkmal'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='issn',
            field=DBentry.fields.ISSNField(blank=True, help_text='EAN (Barcode Nummer) Angaben erlaubt. Die ISSN wird dann daraus ermittelt.', max_length=9, verbose_name='ISSN'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='ort',
            field=models.ForeignKey(blank=True, help_text='Wenn das Magazin regional beschränkt ist, kann die Region hier angegeben werden.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.ort', verbose_name='Herausgabeort'),
        ),
    ]
