# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0066_DBentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='m2m_audio_format',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='m2m_audio_format',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='m2m_audio_format',
            name='format',
        ),
        migrations.AlterField(
            model_name='format',
            name='channel',
            field=models.CharField(blank=True, choices=[('Stereo', 'Stereo'), ('Mono', 'Mono'), ('Quad', 'Quadraphonic'), ('Ambi', 'Ambisonic'), ('Multi', 'Multichannel')], max_length=200),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_autor',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_autor',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.autor'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_band',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_genre',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_musiker',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_ort',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_ort',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_person',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_person',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.person'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_schlagwort',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_schlagwort',
            name='schlagwort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.schlagwort'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_spielort',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_spielort',
            name='spielort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.spielort'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_veranstaltung',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_veranstaltung',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.veranstaltung'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_band',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_band',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.band'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_genre',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_musiker',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_ort',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_ort',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_person',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_person',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.person'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_schlagwort',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_schlagwort',
            name='schlagwort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.schlagwort'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_spielort',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_spielort',
            name='spielort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.spielort'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_veranstaltung',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_veranstaltung',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.veranstaltung'),
        ),
        migrations.AlterField(
            model_name='m2m_autor_magazin',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.autor'),
        ),
        migrations.AlterField(
            model_name='m2m_band_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='m2m_band_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_bildmaterial_ort',
            name='bildmaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.bildmaterial'),
        ),
        migrations.AlterField(
            model_name='m2m_bildmaterial_ort',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='m2m_buch_autor',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.autor'),
        ),
        migrations.AlterField(
            model_name='m2m_buch_autor',
            name='buch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.buch'),
        ),
        migrations.AlterField(
            model_name='m2m_buch_ort',
            name='buch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.buch'),
        ),
        migrations.AlterField(
            model_name='m2m_buch_ort',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='m2m_dokument_ort',
            name='dokument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.dokument'),
        ),
        migrations.AlterField(
            model_name='m2m_dokument_ort',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='m2m_magazin_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='m2m_magazin_genre',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.magazin'),
        ),
        migrations.AlterField(
            model_name='m2m_memorabilien_ort',
            name='memorabilien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.memorabilien'),
        ),
        migrations.AlterField(
            model_name='m2m_memorabilien_ort',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='m2m_musiker_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='m2m_musiker_genre',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_musiker_instrument',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.instrument'),
        ),
        migrations.AlterField(
            model_name='m2m_musiker_instrument',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_veranstaltung_band',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.band'),
        ),
        migrations.AlterField(
            model_name='m2m_veranstaltung_band',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.veranstaltung'),
        ),
        migrations.AlterField(
            model_name='m2m_veranstaltung_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='m2m_veranstaltung_genre',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.veranstaltung'),
        ),
        migrations.AlterField(
            model_name='m2m_veranstaltung_person',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.person'),
        ),
        migrations.AlterField(
            model_name='m2m_veranstaltung_person',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.veranstaltung'),
        ),
        migrations.AlterField(
            model_name='m2m_video_band',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.band'),
        ),
        migrations.AlterField(
            model_name='m2m_video_band',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.video'),
        ),
        migrations.AlterField(
            model_name='m2m_video_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='m2m_video_genre',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.video'),
        ),
        migrations.AlterField(
            model_name='m2m_video_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_video_musiker',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.video'),
        ),
        migrations.AlterField(
            model_name='m2m_video_ort',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='m2m_video_ort',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.video'),
        ),
        migrations.AlterField(
            model_name='m2m_video_person',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.person'),
        ),
        migrations.AlterField(
            model_name='m2m_video_person',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.video'),
        ),
        migrations.AlterField(
            model_name='m2m_video_schlagwort',
            name='schlagwort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.schlagwort'),
        ),
        migrations.AlterField(
            model_name='m2m_video_schlagwort',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.video'),
        ),
        migrations.AlterField(
            model_name='m2m_video_spielort',
            name='spielort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.spielort'),
        ),
        migrations.AlterField(
            model_name='m2m_video_spielort',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.video'),
        ),
        migrations.AlterField(
            model_name='m2m_video_veranstaltung',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.veranstaltung'),
        ),
        migrations.AlterField(
            model_name='m2m_video_veranstaltung',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.video'),
        ),
        migrations.DeleteModel(
            name='m2m_audio_format',
        ),
    ]
