# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DBentry', '0067_DBentry_m2m_rework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoriten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_genres', models.ManyToManyField(blank=True, to='DBentry.genre', verbose_name='Favoriten: Genre')),
                ('fav_schl', models.ManyToManyField(blank=True, to='DBentry.schlagwort', verbose_name='Favoriten: Schlagworte')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='datei',
            name='datei_media',
            field=models.FileField(blank=True, editable=False, help_text='Datei auf Datenbank-Server hoch- bzw herunterladen.', null=True, upload_to='', verbose_name='Datei'),
        ),
    ]
