# Generated by Django 2.2 on 2019-10-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0068_removed_audio_quelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datei',
            name='quelle',
        ),
    ]
