# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0068_DBentry_Favoriten'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status',
        ),
        migrations.DeleteModel(
            name='turnus',
        ),
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['titel'], 'verbose_name': 'Audio Material', 'verbose_name_plural': 'Audio Materialien'},
        ),
        migrations.AlterModelOptions(
            name='bildmaterial',
            options={'ordering': ['titel'], 'verbose_name': 'Bild Material', 'verbose_name_plural': 'Bild Materialien'},
        ),
        migrations.AlterModelOptions(
            name='buch',
            options={'ordering': ['titel'], 'verbose_name': 'Buch', 'verbose_name_plural': 'Bücher'},
        ),
        migrations.AlterModelOptions(
            name='buch_serie',
            options={'ordering': ['serie'], 'verbose_name': 'Buchserie', 'verbose_name_plural': 'Buchserien'},
        ),
        migrations.AlterModelOptions(
            name='dokument',
            options={'ordering': ['titel'], 'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumente'},
        ),
        migrations.AlterModelOptions(
            name='formatsize',
            options={'ordering': ['size'], 'verbose_name': 'Format-Größe', 'verbose_name_plural': 'Format-Größen'},
        ),
        migrations.AlterModelOptions(
            name='formattyp',
            options={'ordering': ['typ'], 'verbose_name': 'Format-Typ', 'verbose_name_plural': 'Format-Typen'},
        ),
        migrations.AlterModelOptions(
            name='geber',
            options={'ordering': ['name'], 'verbose_name': 'Geber', 'verbose_name_plural': 'Geber'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['instrument', 'kuerzel'], 'verbose_name': 'Instrument', 'verbose_name_plural': 'Instrumente'},
        ),
        migrations.AlterModelOptions(
            name='kreis',
            options={'ordering': ['name', 'bland'], 'verbose_name': 'Kreis', 'verbose_name_plural': 'Kreise'},
        ),
        migrations.AlterModelOptions(
            name='noisered',
            options={'ordering': ['verfahren'], 'verbose_name': 'Noise Reduction Verfahren', 'verbose_name_plural': 'Noise Reduction Verfahren'},
        ),
        migrations.AlterModelOptions(
            name='provenienz',
            options={'ordering': ['geber', 'typ'], 'verbose_name': 'Provenienz', 'verbose_name_plural': 'Provenienzen'},
        ),
        migrations.AlterField(
            model_name='favoriten',
            name='fav_genres',
            field=models.ManyToManyField(blank=True, to='DBentry.genre', verbose_name='Favoriten Genre'),
        ),
        migrations.AlterField(
            model_name='favoriten',
            name='fav_schl',
            field=models.ManyToManyField(blank=True, to='DBentry.schlagwort', verbose_name='Favoriten Schlagworte'),
        ),
        migrations.AlterField(
            model_name='favoriten',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
