# Generated by Django 2.2 on 2019-10-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0069_removed_datei_quelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='sender',
        ),
    ]
