# Generated by Django 2.2 on 2019-10-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0070_removed_audio_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='tape',
        ),
    ]
