# Generated by Django 2.2 on 2019-10-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0071_removed_Format_tape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='format',
            name='channel',
        ),
    ]
