# Generated by Django 2.2 on 2019-10-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0073_removed_Format_noise_red'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoiseRed',
        ),
    ]
