# Generated by Django 2.2 on 2019-10-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0074_delete_model_NoiseRed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazin',
            name='turnus',
        ),
    ]
