# Generated by Django 2.2 on 2019-10-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0075_remove_magazin_turnus'),
    ]

    operations = [
        migrations.AddField(
            model_name='herausgeber',
            name='herausgeber',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
