# Generated by Django 2.2 on 2019-10-24 07:41
# Fill the Herausgeber.herausgeber field with values from Herausgeber._name.

from django.db import migrations, models


def forwards(apps, schema_editor):
    """Copy the values of the '_name' field to the 'herausgeber' field."""
    Herausgeber = apps.get_model('DBentry', 'Herausgeber')
    db_alias = schema_editor.connection.alias
    Herausgeber.objects.using(db_alias).update(herausgeber=models.F('_name'))


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0076_add_herausgeber_herausgeber'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop, elidable=True)
    ]
