# Generated by Django 2.2 on 2019-10-24 08:23
# Change Herausgeber's parent from ComputedNameModel to BaseModel.
# This includes removing the inherited fields '_name' and '_changed_flag'.
# Additionally, remove the fields 'person' and 'organisation';
# Their functionality is now entirely carried by the field 'herausgeber'.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0077_data_herausgeber_herausgeber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herausgeber',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['herausgeber'], 'verbose_name': 'Herausgeber', 'verbose_name_plural': 'Herausgeber'},
        ),
        migrations.RemoveField(
            model_name='herausgeber',
            name='_changed_flag',
        ),
        migrations.RemoveField(
            model_name='herausgeber',
            name='_name',
        ),
        migrations.RemoveField(
            model_name='herausgeber',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='herausgeber',
            name='person',
        ),
    ]
