# Generated by Django 2.2 on 2019-10-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0078_simplify_model_herausgeber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
