# Generated by Django 2.2 on 2019-10-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0080_delete_model_kreis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender_alias',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='datei',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='video',
            name='sender',
        ),
        migrations.DeleteModel(
            name='sender',
        ),
        migrations.DeleteModel(
            name='sender_alias',
        ),
    ]
