# Generated by Django 2.2 on 2019-10-28 08:15
# Change audio.tracks from IntegerField to PositiveIntegerField.

from django.db import migrations, models


def forwards(apps, schema_editor):
    """Set any negative values of IntegerField audio.tracks to None."""
    audio = apps.get_model('DBentry', 'audio')
    db_alias = schema_editor.connection.alias
    audio.objects.using(db_alias).filter(tracks__lt=0).update(tracks=None)


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0082_rename_buch_sprache'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='audio',
            name='tracks',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Anz. Tracks'),
        ),
    ]
