# Generated by Django 2.2 on 2019-10-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0083_alter_audio_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='discogs_url',
            field=models.URLField(blank=True, help_text='Adresse zur discogs.com Seite dieses Objektes.', verbose_name='Link discogs.com'),
        ),
    ]
