# Generated by Django 2.2 on 2019-10-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0084_help_audio_discogs_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m2m_magazin_herausgeber',
            name='end',
        ),
        migrations.RemoveField(
            model_name='m2m_magazin_herausgeber',
            name='start',
        ),
    ]
