# Generated by Django 2.2 on 2019-10-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0085_removed_temporal_fields_m2m_magazin_herausgeber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m2m_magazin_verlag',
            name='end',
        ),
        migrations.RemoveField(
            model_name='m2m_magazin_verlag',
            name='start',
        ),
    ]
