# Generated by Django 2.2 on 2019-10-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0086_removed_temporal_fields_m2m_magazin_verlag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildmaterial',
            name='reihe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='DBentry.Bildreihe', verbose_name='Bildreihe'),
        ),
    ]
