# Generated by Django 2.2 on 2020-07-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0087_alter_bildmaterial_reihe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['ausgabe__magazin__magazin_name', 'ausgabe___name', 'seite', 'pk'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
    ]
