# Generated by Django 2.2 on 2020-07-09 09:35

import DBentry.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0089_buch_verlag_to_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='e_jahr',
            field=DBentry.fields.YearField(blank=True, null=True, verbose_name='Jahr'),
        ),
    ]
