# Generated by Django 2.2 on 2020-07-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0090_audio_e_jahr_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='ober',
        ),
    ]
