# Generated by Django 2.2 on 2020-07-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0091_remove_genre_ober'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schlagwort',
            name='ober',
        ),
    ]
