# Generated by Django 2.2 on 2020-07-20 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0092_remove_schlagwort_ober'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['ausgabe__magazin__magazin_name', 'ausgabe___name', 'seite', 'schlagzeile'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterModelOptions(
            name='band_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='datei',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['titel'], 'verbose_name': 'Datei', 'verbose_name_plural': 'Dateien'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['_name'], 'verbose_name': 'Format', 'verbose_name_plural': 'Formate'},
        ),
        migrations.AlterModelOptions(
            name='genre_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='instrument_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='lagerort',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['_name'], 'verbose_name': 'Lagerort', 'verbose_name_plural': 'Lagerorte'},
        ),
        migrations.AlterModelOptions(
            name='land_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='musiker',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['kuenstler_name'], 'verbose_name': 'Musiker', 'verbose_name_plural': 'Musiker'},
        ),
        migrations.AlterModelOptions(
            name='musiker_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='schlagwort_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='spielort',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['name', 'ort'], 'verbose_name': 'Spielort', 'verbose_name_plural': 'Spielorte'},
        ),
        migrations.AlterModelOptions(
            name='spielort_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='veranstaltung_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
    ]
