# Generated by Django 2.2 on 2020-07-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0093_set_meta_ordering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='instrument_alias',
        ),
    ]
