# Generated by Django 2.2 on 2020-07-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0094_delete_model_instrument_alias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='land_alias',
        ),
    ]
