# Generated by Django 2.2 on 2020-07-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0095_delete_model_land_alias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favoriten',
        ),
    ]
