# Generated by Django 2.2.13 on 2020-08-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0096_delete_model_favoriten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='schlagwort',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_schlagwort', to='DBentry.schlagwort'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='seite',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.magazin'),
        ),
        migrations.AlterField(
            model_name='bundesland',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.land'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.land'),
        ),
    ]
