# Generated by Django 2.2.13 on 2020-08-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0097_changed_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausgabe',
            name='audio',
            field=models.ManyToManyField(through='DBentry.m2m_audio_ausgabe', to='DBentry.audio'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='magazin',
            field=models.ManyToManyField(through='DBentry.m2m_autor_magazin', to='DBentry.magazin'),
        ),
        migrations.AlterField(
            model_name='band',
            name='orte',
            field=models.ManyToManyField(to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_magazin_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='musiker',
            name='orte',
            field=models.ManyToManyField(to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='person',
            name='orte',
            field=models.ManyToManyField(to='DBentry.ort'),
        ),
    ]
