# Generated by Django 2.2.13 on 2020-08-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0098_removed_some_blank_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochureurl',
            name='brochure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='DBentry.BaseBrochure'),
        ),
        migrations.AlterField(
            model_name='brochureyear',
            name='brochure',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jahre', to='DBentry.BaseBrochure'),
            preserve_default=False,
        ),
    ]
