# Generated by Django 2.2.13 on 2020-08-20 10:08

from django.db import migrations, models


def truncate_kuerzel(apps, schema_editor):
    """Truncate autor.kuerzel to max length of 8."""
    from django.db.models.functions import Length, Substr
    autor = apps.get_model('DBentry', 'autor')
    (
        autor.objects
        .annotate(length=Length('kuerzel'))
        .filter(length__gt=8)
        .update(kuerzel=Substr('kuerzel', 1, 8))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0099_removed_blank_null_from_brochure_related'),
    ]

    operations = [
        migrations.RunPython(truncate_kuerzel, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name='autor',
            name='kuerzel',
            field=models.CharField(blank=True, max_length=8, verbose_name='Kürzel'),
        ),
    ]
