# Generated by Django 2.2.13 on 2020-08-20 10:43

from django.db import migrations, models


def truncate_kuerzel(apps, schema_editor):
    """Truncate instrument.kuerzel to max length of 8."""
    from django.db.models.functions import Length, Substr
    instrument = apps.get_model('DBentry', 'instrument')
    (
        instrument.objects
        .annotate(length=Length('kuerzel'))
        .filter(length__gt=8)
        .update(kuerzel=Substr('kuerzel', 1, 8))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0100_reduced_autor_kuerzel_maxlength'),
    ]

    operations = [
        migrations.RunPython(truncate_kuerzel, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name='instrument',
            name='kuerzel',
            field=models.CharField(blank=True, max_length=8, verbose_name='Kürzel'),
        ),
    ]
