# Generated by Django 2.2.13 on 2020-08-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0101_reduced_instrument_kuerzel_maxlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazin',
            name='ausgaben_merkmal',
            field=models.CharField(blank=True, choices=[('num', 'Nummer'), ('lnum', 'Lfd.Nummer'), ('monat', 'Monat'), ('e_datum', 'Ersch.Datum')], help_text='Das dominante Merkmal der Ausgaben. Diese Angabe bestimmt die Darstellung der Ausgaben in der Änderungsliste.', max_length=8, verbose_name='Ausgaben Merkmal'),
        ),
    ]
