# Generated by Django 2.2.13 on 2020-08-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0102_reduced_magazin_ausgaben_merkmal_maxlength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geber',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
