# Generated by Django 2.2.13 on 2020-08-20 10:59

import DBentry.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0103_removed_geber_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildmaterial',
            name='datum',
            field=DBentry.fields.PartialDateField(blank=True, help_text='Teilweise Angaben sind erlaubt (z.B. Jahr & Monat aber ohne Tag).', max_length=10, verbose_name='Zeitangabe'),
        ),
    ]
