# Generated by Django 2.2.13 on 2020-08-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0104_alter_bildmaterial_datum_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veranstaltung',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung bzgl. der Veranstaltung'),
        ),
    ]
