# Generated by Django 2.2.13 on 2020-08-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0105_add_veranstaltung_beschreibung_helptext'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ausgabe_lnum',
            unique_together={('lnum', 'ausgabe')},
        ),
        migrations.AlterUniqueTogether(
            name='ausgabe_num',
            unique_together={('num', 'ausgabe')},
        ),
        migrations.RemoveField(
            model_name='ausgabe_lnum',
            name='kuerzel',
        ),
        migrations.RemoveField(
            model_name='ausgabe_num',
            name='kuerzel',
        ),
    ]
