# Generated by Django 2.2.13 on 2020-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0106_removed_ausgabe_kuerzel_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tracks',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Anz. Tracks'),
        ),
    ]
