# Generated by Django 2.2.13 on 2020-08-21 07:04

from django.db import migrations, models, transaction
import django.db.models.deletion


@transaction.atomic
def forwards(apps, schema_editor):
    magazin = apps.get_model('DBentry', 'magazin')
    for m in magazin.objects.exclude(ort__isnull=True):
        m.orte.add(m.ort)


@transaction.atomic
def reverse(apps, schema_editor):
    ort = apps.get_model('DBentry', 'ort')
    for o in ort.objects.exclude(magazin__isnull=True):
        o.magazin_set.filter(ort__isnull=True).update(ort=o)


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0107_alter_video_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazin',
            name='ort',
            field=models.ForeignKey(blank=True, help_text='Wenn das Magazin regional beschränkt ist, kann die Region hier angegeben werden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ort_old', to='DBentry.ort', verbose_name='Herausgabeort'),
        ),
        migrations.AddField(
            model_name='magazin',
            name='orte',
            field=models.ManyToManyField(to='DBentry.ort'),
        ),
        migrations.RunPython(forwards, reverse, elidable=True),
        migrations.RemoveField(
            model_name='magazin',
            name='ort',
        ),
    ]
