# Generated by Django 2.2.13 on 2020-08-24 06:58

from django.db import migrations, models


def make_positive(apps, schema_editor):
    """Convert any negative num/lnum values to postive ones."""
    ausgabe_num = apps.get_model('DBentry', 'ausgabe_num')
    ausgabe_lnum = apps.get_model('DBentry', 'ausgabe_lnum')
    ausgabe_num.objects.filter(num__lt=0).update(num=models.F('num') * -1)
    ausgabe_lnum.objects.filter(lnum__lt=0).update(lnum=models.F('lnum') * -1)


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0108_magazin_ort_m2m'),
    ]

    operations = [
        migrations.RunPython(make_positive, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name='ausgabe_lnum',
            name='lnum',
            field=models.PositiveSmallIntegerField(verbose_name='Lfd. Nummer'),
        ),
        migrations.AlterField(
            model_name='ausgabe_num',
            name='num',
            field=models.PositiveSmallIntegerField(verbose_name='Nummer'),
        ),
    ]
