# Generated by Django 2.2.13 on 2020-08-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0109_alter_num_lnum_positive_integerfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['ausgabe__magazin__magazin_name', 'ausgabe___name', 'seite', 'schlagzeile'], 'verbose_name': 'Artikel', 'verbose_name_plural': 'Artikel'},
        ),
        migrations.AlterModelOptions(
            name='audio',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'permissions': [('alter_bestand_audio', 'Aktion: Bestand/Dublette hinzufügen.')], 'verbose_name': 'Audio Material', 'verbose_name_plural': 'Audio Materialien'},
        ),
        migrations.AlterModelOptions(
            name='ausgabe',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['magazin'], 'permissions': [('alter_bestand_ausgabe', 'Aktion: Bestand/Dublette hinzufügen.')], 'verbose_name': 'Ausgabe', 'verbose_name_plural': 'Ausgaben'},
        ),
        migrations.AlterModelOptions(
            name='ausgabe_jahr',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['jahr'], 'verbose_name': 'Jahr', 'verbose_name_plural': 'Jahre'},
        ),
        migrations.AlterModelOptions(
            name='ausgabe_lnum',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['lnum'], 'verbose_name': 'lfd. Nummer', 'verbose_name_plural': 'Laufende Nummer'},
        ),
        migrations.AlterModelOptions(
            name='ausgabe_monat',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['monat'], 'verbose_name': 'Ausgabe-Monat', 'verbose_name_plural': 'Ausgabe-Monate'},
        ),
        migrations.AlterModelOptions(
            name='ausgabe_num',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['num'], 'verbose_name': 'Nummer', 'verbose_name_plural': 'Ausgabennummer'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['_name'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autoren'},
        ),
        migrations.AlterModelOptions(
            name='band',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['band_name'], 'verbose_name': 'Band', 'verbose_name_plural': 'Bands'},
        ),
        migrations.AlterModelOptions(
            name='band_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='basebrochure',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel']},
        ),
        migrations.AlterModelOptions(
            name='bestand',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['pk'], 'verbose_name': 'Bestand', 'verbose_name_plural': 'Bestände'},
        ),
        migrations.AlterModelOptions(
            name='bildmaterial',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'permissions': [('alter_bestand_bildmaterial', 'Aktion: Bestand/Dublette hinzufügen.')], 'verbose_name': 'Bild Material', 'verbose_name_plural': 'Bild Materialien'},
        ),
        migrations.AlterModelOptions(
            name='bildreihe',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['name'], 'verbose_name': 'Bildreihe', 'verbose_name_plural': 'Bildreihen'},
        ),
        migrations.AlterModelOptions(
            name='brochure',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'verbose_name': 'Broschüre', 'verbose_name_plural': 'Broschüren'},
        ),
        migrations.AlterModelOptions(
            name='brochureurl',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'verbose_name': 'Web-Adresse', 'verbose_name_plural': 'Web-Adressen'},
        ),
        migrations.AlterModelOptions(
            name='brochureyear',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['jahr'], 'verbose_name': 'Jahr', 'verbose_name_plural': 'Jahre'},
        ),
        migrations.AlterModelOptions(
            name='buch',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'permissions': [('alter_bestand_buch', 'Aktion: Bestand/Dublette hinzufügen.')], 'verbose_name': 'Buch', 'verbose_name_plural': 'Bücher'},
        ),
        migrations.AlterModelOptions(
            name='bundesland',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['land', 'bland_name'], 'verbose_name': 'Bundesland', 'verbose_name_plural': 'Bundesländer'},
        ),
        migrations.AlterModelOptions(
            name='datei',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'verbose_name': 'Datei', 'verbose_name_plural': 'Dateien'},
        ),
        migrations.AlterModelOptions(
            name='dokument',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'permissions': [('alter_bestand_dokument', 'Aktion: Bestand/Dublette hinzufügen.')], 'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumente'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['_name'], 'verbose_name': 'Format', 'verbose_name_plural': 'Formate'},
        ),
        migrations.AlterModelOptions(
            name='formatsize',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['size'], 'verbose_name': 'Format-Größe', 'verbose_name_plural': 'Format-Größen'},
        ),
        migrations.AlterModelOptions(
            name='formattag',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['tag'], 'verbose_name': 'Format-Tag', 'verbose_name_plural': 'Format-Tags'},
        ),
        migrations.AlterModelOptions(
            name='formattyp',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['typ'], 'verbose_name': 'Format-Typ', 'verbose_name_plural': 'Format-Typen'},
        ),
        migrations.AlterModelOptions(
            name='geber',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['name'], 'verbose_name': 'Geber', 'verbose_name_plural': 'Geber'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['genre'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='genre_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='herausgeber',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['herausgeber'], 'verbose_name': 'Herausgeber', 'verbose_name_plural': 'Herausgeber'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['instrument', 'kuerzel'], 'verbose_name': 'Instrument', 'verbose_name_plural': 'Instrumente'},
        ),
        migrations.AlterModelOptions(
            name='kalendar',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'verbose_name': 'Programmheft', 'verbose_name_plural': 'Programmhefte'},
        ),
        migrations.AlterModelOptions(
            name='katalog',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'verbose_name': 'Warenkatalog', 'verbose_name_plural': 'Warenkataloge'},
        ),
        migrations.AlterModelOptions(
            name='lagerort',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['_name'], 'verbose_name': 'Lagerort', 'verbose_name_plural': 'Lagerorte'},
        ),
        migrations.AlterModelOptions(
            name='land',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['land_name'], 'verbose_name': 'Land', 'verbose_name_plural': 'Länder'},
        ),
        migrations.AlterModelOptions(
            name='magazin',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['magazin_name'], 'verbose_name': 'Magazin', 'verbose_name_plural': 'Magazine'},
        ),
        migrations.AlterModelOptions(
            name='memorabilien',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'permissions': [('alter_bestand_memorabilien', 'Aktion: Bestand/Dublette hinzufügen.')], 'verbose_name': 'Memorabilia', 'verbose_name_plural': 'Memorabilien'},
        ),
        migrations.AlterModelOptions(
            name='monat',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['ordinal'], 'verbose_name': 'Monat', 'verbose_name_plural': 'Monate'},
        ),
        migrations.AlterModelOptions(
            name='musiker',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['kuenstler_name'], 'verbose_name': 'Musiker', 'verbose_name_plural': 'Musiker'},
        ),
        migrations.AlterModelOptions(
            name='musiker_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='ort',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['land', 'bland', 'stadt'], 'verbose_name': 'Ort', 'verbose_name_plural': 'Orte'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
        migrations.AlterModelOptions(
            name='plattenfirma',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['name'], 'verbose_name': 'Plattenfirma', 'verbose_name_plural': 'Plattenfirmen'},
        ),
        migrations.AlterModelOptions(
            name='provenienz',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['geber', 'typ'], 'verbose_name': 'Provenienz', 'verbose_name_plural': 'Provenienzen'},
        ),
        migrations.AlterModelOptions(
            name='schlagwort',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['schlagwort'], 'verbose_name': 'Schlagwort', 'verbose_name_plural': 'Schlagwörter'},
        ),
        migrations.AlterModelOptions(
            name='schlagwort_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='schriftenreihe',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['name'], 'verbose_name': 'Schriftenreihe', 'verbose_name_plural': 'Schriftenreihen'},
        ),
        migrations.AlterModelOptions(
            name='spielort',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['name', 'ort'], 'verbose_name': 'Spielort', 'verbose_name_plural': 'Spielorte'},
        ),
        migrations.AlterModelOptions(
            name='spielort_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='technik',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'permissions': [('alter_bestand_technik', 'Aktion: Bestand/Dublette hinzufügen.')], 'verbose_name': 'Technik', 'verbose_name_plural': 'Technik'},
        ),
        migrations.AlterModelOptions(
            name='veranstaltung',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['name', 'datum', 'spielort'], 'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.AlterModelOptions(
            name='veranstaltung_alias',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['alias'], 'verbose_name': 'Alias'},
        ),
        migrations.AlterModelOptions(
            name='veranstaltungsreihe',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['name'], 'verbose_name': 'Veranstaltungsreihe', 'verbose_name_plural': 'Veranstaltungsreihen'},
        ),
        migrations.AlterModelOptions(
            name='verlag',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['verlag_name', 'sitz'], 'verbose_name': 'Verlag', 'verbose_name_plural': 'Verlage'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'default_permissions': ('add', 'change', 'delete', 'merge', 'view'), 'ordering': ['titel'], 'permissions': [('alter_bestand_video', 'Aktion: Bestand/Dublette hinzufügen.')], 'verbose_name': 'Video Material', 'verbose_name_plural': 'Video Materialien'},
        ),
    ]
