# Generated by Django 2.2.13 on 2020-08-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0110_add_view_perm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brochure',
            options={'verbose_name': 'Broschüre', 'verbose_name_plural': 'Broschüren'},
        ),
        migrations.AlterModelOptions(
            name='kalendar',
            options={'verbose_name': 'Programmheft', 'verbose_name_plural': 'Programmhefte'},
        ),
        migrations.AlterModelOptions(
            name='katalog',
            options={'verbose_name': 'Warenkatalog', 'verbose_name_plural': 'Warenkataloge'},
        ),
    ]
