# Generated by Django 2.2.13 on 2020-08-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0112_magazin_urls_m2o'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildmaterial',
            name='signatur',
            field=models.CharField(blank=True, help_text='Kürzel bestehend aus Angabe zur Größe und einer 5-stelligen fortlaufenden Nummer. Z.B.: DINA2-00395', max_length=200, null=True, unique=True),
        ),
    ]
