# Generated by Django 2.2.13 on 2020-08-26 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0113_bildmaterial_signatur_helptext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ausgabe_jahr',
            new_name='AusgabeJahr',
        ),
        migrations.RenameModel(
            old_name='ausgabe_lnum',
            new_name='AusgabeLnum',
        ),
        migrations.RenameModel(
            old_name='ausgabe_monat',
            new_name='AusgabeMonat',
        ),
        migrations.RenameModel(
            old_name='ausgabe_num',
            new_name='AusgabeNum',
        ),
        migrations.RenameModel(
            old_name='band_alias',
            new_name='BandAlias',
        ),
        migrations.RenameModel(
            old_name='genre_alias',
            new_name='GenreAlias',
        ),
        migrations.RenameModel(
            old_name='musiker_alias',
            new_name='MusikerAlias',
        ),
        migrations.RenameModel(
            old_name='schlagwort_alias',
            new_name='SchlagwortAlias',
        ),
        migrations.RenameModel(
            old_name='spielort_alias',
            new_name='SpielortAlias',
        ),
        migrations.RenameModel(
            old_name='veranstaltung_alias',
            new_name='VeranstaltungAlias',
        ),
        migrations.AlterField(
            model_name='artikel',
            name='ausgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.Ausgabe'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='autor',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_autor', to='DBentry.Autor'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='band',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_band', to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_genre', to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='musiker',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_musiker', to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='ort',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_ort', to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='person',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_person', to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='schlagwort',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_schlagwort', to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='spielort',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_spielort', to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='veranstaltung',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_veranstaltung', to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='band',
            field=models.ManyToManyField(through='DBentry.m2m_audio_band', to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_audio_genre', to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='musiker',
            field=models.ManyToManyField(through='DBentry.m2m_audio_musiker', to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='ort',
            field=models.ManyToManyField(through='DBentry.m2m_audio_ort', to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='person',
            field=models.ManyToManyField(through='DBentry.m2m_audio_person', to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='plattenfirma',
            field=models.ManyToManyField(through='DBentry.m2m_audio_plattenfirma', to='DBentry.Plattenfirma'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='schlagwort',
            field=models.ManyToManyField(through='DBentry.m2m_audio_schlagwort', to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='spielort',
            field=models.ManyToManyField(through='DBentry.m2m_audio_spielort', to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='veranstaltung',
            field=models.ManyToManyField(through='DBentry.m2m_audio_veranstaltung', to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='audio',
            field=models.ManyToManyField(through='DBentry.m2m_audio_ausgabe', to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='ausgabe',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.Magazin'),
        ),
        migrations.AlterField(
            model_name='ausgabejahr',
            name='ausgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Ausgabe'),
        ),
        migrations.AlterField(
            model_name='ausgabelnum',
            name='ausgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Ausgabe'),
        ),
        migrations.AlterField(
            model_name='ausgabemonat',
            name='ausgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Ausgabe'),
        ),
        migrations.AlterField(
            model_name='ausgabemonat',
            name='monat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Monat'),
        ),
        migrations.AlterField(
            model_name='ausgabenum',
            name='ausgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Ausgabe'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='magazin',
            field=models.ManyToManyField(through='DBentry.m2m_autor_magazin', to='DBentry.Magazin'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_band_genre', to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='band',
            name='musiker',
            field=models.ManyToManyField(through='DBentry.m2m_band_musiker', to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='band',
            name='orte',
            field=models.ManyToManyField(to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='bandalias',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='basebrochure',
            name='ausgabe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beilagen', to='DBentry.Ausgabe', verbose_name='Ausgabe'),
        ),
        migrations.AlterField(
            model_name='basebrochure',
            name='genre',
            field=models.ManyToManyField(to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='ausgabe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.Ausgabe'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='bildmaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.Bildmaterial'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='buch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.Buch'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='dokument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.Dokument'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='lagerort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.Lagerort'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='memorabilien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.Memorabilien'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='provenienz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Provenienz'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='technik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.Technik'),
        ),
        migrations.AlterField(
            model_name='bestand',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DBentry.Video'),
        ),
        migrations.AlterField(
            model_name='bildmaterial',
            name='band',
            field=models.ManyToManyField(to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='bildmaterial',
            name='genre',
            field=models.ManyToManyField(to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='bildmaterial',
            name='musiker',
            field=models.ManyToManyField(to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='bildmaterial',
            name='ort',
            field=models.ManyToManyField(to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='bildmaterial',
            name='person',
            field=models.ManyToManyField(to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='bildmaterial',
            name='schlagwort',
            field=models.ManyToManyField(to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='bildmaterial',
            name='spielort',
            field=models.ManyToManyField(to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='bildmaterial',
            name='veranstaltung',
            field=models.ManyToManyField(to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='schlagwort',
            field=models.ManyToManyField(to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='autor',
            field=models.ManyToManyField(to='DBentry.Autor'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='band',
            field=models.ManyToManyField(to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='buchband',
            field=models.ForeignKey(blank=True, help_text='Der Sammelband, der diesen Aufsatz enthält.', limit_choices_to={'is_buchband': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buch_set', to='DBentry.Buch', verbose_name='Sammelband'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='genre',
            field=models.ManyToManyField(to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='musiker',
            field=models.ManyToManyField(to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='ort',
            field=models.ManyToManyField(to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='person',
            field=models.ManyToManyField(to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='schlagwort',
            field=models.ManyToManyField(to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='schriftenreihe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Schriftenreihe'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='spielort',
            field=models.ManyToManyField(to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='veranstaltung',
            field=models.ManyToManyField(to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='verlag',
            field=models.ManyToManyField(to='DBentry.Verlag'),
        ),
        migrations.AlterField(
            model_name='bundesland',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.Land'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='band',
            field=models.ManyToManyField(to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='genre',
            field=models.ManyToManyField(to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='musiker',
            field=models.ManyToManyField(through='DBentry.m2m_datei_musiker', to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='ort',
            field=models.ManyToManyField(to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='person',
            field=models.ManyToManyField(to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='provenienz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Provenienz'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='schlagwort',
            field=models.ManyToManyField(to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='spielort',
            field=models.ManyToManyField(to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='datei',
            name='veranstaltung',
            field=models.ManyToManyField(to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='band',
            field=models.ManyToManyField(to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='genre',
            field=models.ManyToManyField(to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='musiker',
            field=models.ManyToManyField(to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='ort',
            field=models.ManyToManyField(to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='person',
            field=models.ManyToManyField(to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='schlagwort',
            field=models.ManyToManyField(to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='spielort',
            field=models.ManyToManyField(to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='veranstaltung',
            field=models.ManyToManyField(to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='format',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='genrealias',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='kalendar',
            name='spielort',
            field=models.ManyToManyField(to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='kalendar',
            name='veranstaltung',
            field=models.ManyToManyField(to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_autor',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_autor',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Autor'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_band',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_band',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_genre',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_musiker',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_ort',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_ort',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_person',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_person',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_schlagwort',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_schlagwort',
            name='schlagwort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_spielort',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_spielort',
            name='spielort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_veranstaltung',
            name='artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Artikel'),
        ),
        migrations.AlterField(
            model_name='m2m_artikel_veranstaltung',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_ausgabe',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_ausgabe',
            name='ausgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Ausgabe'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_band',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_band',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_genre',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_musiker',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_musiker',
            name='instrument',
            field=models.ManyToManyField(blank=True, to='DBentry.Instrument', verbose_name='Instrumente'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_ort',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_ort',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_person',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_person',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_plattenfirma',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_plattenfirma',
            name='plattenfirma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Plattenfirma'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_schlagwort',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_schlagwort',
            name='schlagwort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_spielort',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_spielort',
            name='spielort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_veranstaltung',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='m2m_audio_veranstaltung',
            name='veranstaltung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='m2m_autor_magazin',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Autor'),
        ),
        migrations.AlterField(
            model_name='m2m_autor_magazin',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Magazin'),
        ),
        migrations.AlterField(
            model_name='m2m_band_genre',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='m2m_band_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='m2m_band_musiker',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='m2m_band_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_datei_musiker',
            name='datei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Datei'),
        ),
        migrations.AlterField(
            model_name='m2m_datei_musiker',
            name='instrument',
            field=models.ManyToManyField(blank=True, to='DBentry.Instrument', verbose_name='Instrumente'),
        ),
        migrations.AlterField(
            model_name='m2m_datei_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_datei_quelle',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Audio'),
        ),
        migrations.AlterField(
            model_name='m2m_datei_quelle',
            name='bildmaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Bildmaterial'),
        ),
        migrations.AlterField(
            model_name='m2m_datei_quelle',
            name='buch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Buch'),
        ),
        migrations.AlterField(
            model_name='m2m_datei_quelle',
            name='datei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Datei'),
        ),
        migrations.AlterField(
            model_name='m2m_datei_quelle',
            name='dokument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Dokument'),
        ),
        migrations.AlterField(
            model_name='m2m_datei_quelle',
            name='memorabilien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Memorabilien'),
        ),
        migrations.AlterField(
            model_name='m2m_datei_quelle',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Video'),
        ),
        migrations.AlterField(
            model_name='m2m_magazin_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='m2m_magazin_genre',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Magazin'),
        ),
        migrations.AlterField(
            model_name='m2m_magazin_herausgeber',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Magazin'),
        ),
        migrations.AlterField(
            model_name='m2m_magazin_verlag',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Magazin'),
        ),
        migrations.AlterField(
            model_name='m2m_magazin_verlag',
            name='verlag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Verlag'),
        ),
        migrations.AlterField(
            model_name='m2m_musiker_genre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='m2m_musiker_genre',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_musiker_instrument',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Instrument'),
        ),
        migrations.AlterField(
            model_name='m2m_musiker_instrument',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_video_musiker',
            name='instrument',
            field=models.ManyToManyField(blank=True, to='DBentry.Instrument', verbose_name='Instrumente'),
        ),
        migrations.AlterField(
            model_name='m2m_video_musiker',
            name='musiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='m2m_video_musiker',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Video'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_magazin_genre', to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='orte',
            field=models.ManyToManyField(to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='verlag',
            field=models.ManyToManyField(through='DBentry.m2m_magazin_verlag', to='DBentry.Verlag'),
        ),
        migrations.AlterField(
            model_name='magazinurl',
            name='magazin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='DBentry.Magazin'),
        ),
        migrations.AlterField(
            model_name='memorabilien',
            name='band',
            field=models.ManyToManyField(to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='memorabilien',
            name='genre',
            field=models.ManyToManyField(to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='memorabilien',
            name='musiker',
            field=models.ManyToManyField(to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='memorabilien',
            name='ort',
            field=models.ManyToManyField(to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='memorabilien',
            name='person',
            field=models.ManyToManyField(to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='memorabilien',
            name='schlagwort',
            field=models.ManyToManyField(to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='memorabilien',
            name='spielort',
            field=models.ManyToManyField(to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='memorabilien',
            name='veranstaltung',
            field=models.ManyToManyField(to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='musiker',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_musiker_genre', to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='musiker',
            name='instrument',
            field=models.ManyToManyField(through='DBentry.m2m_musiker_instrument', to='DBentry.Instrument'),
        ),
        migrations.AlterField(
            model_name='musiker',
            name='orte',
            field=models.ManyToManyField(to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='musiker',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='musikeralias',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='bland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Bundesland', verbose_name='Bundesland'),
        ),
        migrations.AlterField(
            model_name='ort',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.Land'),
        ),
        migrations.AlterField(
            model_name='person',
            name='orte',
            field=models.ManyToManyField(to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='provenienz',
            name='geber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.Geber'),
        ),
        migrations.AlterField(
            model_name='schlagwortalias',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='spielort',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='spielortalias',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='technik',
            name='band',
            field=models.ManyToManyField(to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='technik',
            name='genre',
            field=models.ManyToManyField(to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='technik',
            name='musiker',
            field=models.ManyToManyField(to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='technik',
            name='ort',
            field=models.ManyToManyField(to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='technik',
            name='person',
            field=models.ManyToManyField(to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='technik',
            name='schlagwort',
            field=models.ManyToManyField(to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='technik',
            name='spielort',
            field=models.ManyToManyField(to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='technik',
            name='veranstaltung',
            field=models.ManyToManyField(to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='band',
            field=models.ManyToManyField(to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='genre',
            field=models.ManyToManyField(to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='musiker',
            field=models.ManyToManyField(to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='person',
            field=models.ManyToManyField(to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='schlagwort',
            field=models.ManyToManyField(to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='spielort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='veranstaltungalias',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBentry.Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='verlag',
            name='sitz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DBentry.Ort'),
        ),
        migrations.AlterField(
            model_name='video',
            name='band',
            field=models.ManyToManyField(to='DBentry.Band'),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(to='DBentry.Genre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='musiker',
            field=models.ManyToManyField(through='DBentry.m2m_video_musiker', to='DBentry.Musiker'),
        ),
        migrations.AlterField(
            model_name='video',
            name='person',
            field=models.ManyToManyField(to='DBentry.Person'),
        ),
        migrations.AlterField(
            model_name='video',
            name='schlagwort',
            field=models.ManyToManyField(to='DBentry.Schlagwort'),
        ),
        migrations.AlterField(
            model_name='video',
            name='spielort',
            field=models.ManyToManyField(to='DBentry.Spielort'),
        ),
        migrations.AlterField(
            model_name='video',
            name='veranstaltung',
            field=models.ManyToManyField(to='DBentry.Veranstaltung'),
        ),
    ]
