import textwrap
from collections import OrderedDict
from functools import cached_property

from django.core.exceptions import FieldDoesNotExist
from django.utils.encoding import force_str
from import_export import widgets
from import_export.fields import Field
from import_export.resources import ModelDeclarativeMetaclass, ModelResource

from dbentry.export.widgets import YesNoBooleanWidget


class AnnotationField(Field):
    """A Resource Field with an annotation expression for the export queryset."""

    def __init__(self, *args, expr=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.expr = expr


class CachedQuerysetField(Field):
    """A Resource Field that returns its export value from a cached queryset."""

    # After a certain amount of joins (from AnnotationField), it is faster to
    # make additional queries instead. Using this field on fields with lots of
    # data (f.ex. musiker or band) speeds up the exporting tremendously: from
    # ~4 minutes for all Artikel objects to 3 secs.

    def __init__(self, *args, queryset=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.queryset = queryset

    @cached_property
    def cache(self):
        cache = {}
        for values_dict in self.queryset.values():
            pk = values_dict.pop(self.queryset.model._meta.pk.name)
            cache[pk] = values_dict
        return cache

    def export(self, obj):
        try:
            return self.cache[obj.pk][self.attribute]
        except KeyError:
            return ""


class MIZDeclarativeMetaclass(ModelDeclarativeMetaclass):
    def __new__(cls, name, bases, attrs):
        # Keep a record of the fields that were declared on this model:
        _declared_fields = OrderedDict()
        for _name, attr in attrs.items():
            if isinstance(attr, Field):
                _declared_fields[_name] = attr

        new_class = super().__new__(cls, name, bases, attrs)

        new_class._meta._declared_fields = _declared_fields

        return new_class


class MIZResource(ModelResource):
    add_annotations = True

    def _add_annotations(self, queryset):
        """Add the annotations declared in `Meta.annotations` to the queryset."""
        if self.add_annotations:
            return queryset.annotate(**self.get_annotations())
        else:
            return queryset

    def filter_export(self, queryset, *args, **kwargs):
        try:
            if queryset.model._meta.get_field("_fts"):
                queryset = queryset.defer("_fts")
        except FieldDoesNotExist:
            pass
        queryset = self._add_annotations(queryset)
        if select_related := getattr(self._meta, "select_related", None):
            queryset = queryset.select_related(*select_related)
        return queryset

    def get_export_headers(self):
        # For fields derived from the model fields, use the field's
        # verbose_name, unless column_name was set:
        headers = []
        for field in self.get_export_fields():
            try:
                model_field = self._meta.model._meta.get_field(field.attribute)
                verbose_name = model_field.verbose_name.capitalize()
            except FieldDoesNotExist:
                verbose_name = field.column_name
            if field.column_name != field.attribute:
                # Not the default column_name
                headers.append(force_str(field.column_name))
            else:
                headers.append(force_str(verbose_name))
        return headers

    def as_string(self):
        """Return a string representation of this model resource class."""

        # This is used to write a class generated by the factory to a file.

        # Stringify the extra fields:
        def string_list_from_expr(original_expr):
            # Inspect the expression to recover the original arguments:
            # string_list expressions: limit(array_to_string(array_agg(...)))
            array_to_string = original_expr._constructor_args[0][0]
            array_agg, sep_expr, default_expr = array_to_string.source_expressions
            path = array_agg.source_expressions[0].name
            sep = sep_expr.value
            if sep != ", ":
                return f'string_list("{path}", sep="{sep}", length=1024)'
            else:
                return f'string_list("{path}", length=1024)'

        field_declarations = []
        if self._meta._declared_fields:
            for name, field in self._meta._declared_fields.items():
                field_kwargs = f'attribute="{field.attribute}", column_name="{field.column_name}"'
                if isinstance(field, AnnotationField):
                    field_kwargs = f"{field_kwargs}, expr={string_list_from_expr(field.expr)},"
                elif isinstance(field, CachedQuerysetField):
                    expr = string_list_from_expr(field.queryset.query.annotations[name])
                    queryset = f"_models.{self._meta.model.__name__}.objects.annotate({name}={expr})"
                    field_kwargs = f"{field_kwargs}, queryset={queryset},"
                field_declarations.append(f"{name} = {field.__class__.__name__}({field_kwargs})")

        # Collect any extra meta:
        extra_meta = []
        if getattr(self._meta, "widgets", None):
            widgets = str(self._meta.widgets).replace("'", '"')
            extra_meta.append(f"widgets = {widgets}")
        if getattr(self._meta, "select_related", None):
            select_related = str(self._meta.select_related).replace("'", '"')
            extra_meta.append(f"select_related = {select_related}")

        indent = " " * 4
        template = textwrap.dedent(
            """
            class %(model_name)sResource(MIZResource):
                %(field_declarations)s
    
                class Meta:
                    model = _models.%(model_name)s
                    fields = %(fields)s
                    export_order = %(fields)s
                    %(extra_meta)s
    
            """
        )
        return template % {
            "model_name": self._meta.model.__name__,
            "field_declarations": f"\n{indent}".join(field_declarations),
            "fields": str(self._meta.fields).replace("'", '"'),
            "extra_meta": f"\n{indent * 2}".join(extra_meta),
        }

    def get_annotations(self):
        """Collect the annotations provided by AnnotationFields."""
        annotations = {}
        for field in self.get_export_fields():
            if isinstance(field, AnnotationField):
                annotations[field.attribute] = field.expr
        return annotations

    @classmethod
    def widget_from_django_field(cls, f, default=widgets.Widget):
        boolean_fields = ("BooleanField", "NullBooleanField")
        if callable(getattr(f, "get_internal_type", None)) and f.get_internal_type() in boolean_fields:
            return YesNoBooleanWidget
        return super().widget_from_django_field(f, default)
