# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0050_DBentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='m2m_artikel_autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.autor')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_musiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('musiker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_ort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('ort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.ort')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.person')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_schlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('schlagwort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.schlagwort')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_spielort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('spielort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.spielort')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_veranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_autor_magazin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.autor')),
                ('magazin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.magazin')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_band_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_band_musiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band')),
                ('musiker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_buch_autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.autor')),
                ('buch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.buch')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_magazin_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
                ('magazin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.magazin')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_musiker_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
                ('musiker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_musiker_instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.instrument')),
                ('musiker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_veranstaltung_band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_veranstaltung_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_veranstaltung_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.person')),
                ('veranstaltung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='m2m_veranstaltung_person',
            unique_together=set([('veranstaltung', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_veranstaltung_genre',
            unique_together=set([('veranstaltung', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_veranstaltung_band',
            unique_together=set([('veranstaltung', 'band')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_musiker_instrument',
            unique_together=set([('musiker', 'instrument')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_musiker_genre',
            unique_together=set([('musiker', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_magazin_genre',
            unique_together=set([('magazin', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_buch_autor',
            unique_together=set([('buch', 'autor')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_band_musiker',
            unique_together=set([('band', 'musiker')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_band_genre',
            unique_together=set([('band', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_autor_magazin',
            unique_together=set([('autor', 'magazin')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_veranstaltung',
            unique_together=set([('artikel', 'veranstaltung')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_spielort',
            unique_together=set([('artikel', 'spielort')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_schlagwort',
            unique_together=set([('artikel', 'schlagwort')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_person',
            unique_together=set([('artikel', 'person')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_ort',
            unique_together=set([('artikel', 'ort')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_musiker',
            unique_together=set([('artikel', 'musiker')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_genre',
            unique_together=set([('artikel', 'genre')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_band',
            unique_together=set([('artikel', 'band')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_autor',
            unique_together=set([('artikel', 'autor')]),
        ),
    ]
