# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0050_DBentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='m2m_artikel_autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.autor')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('band_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_musiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('musiker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_ort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('ort_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.ort')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.person')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_schlagwort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('schlagwort_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.schlagwort')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_spielort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('spielort_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.spielort')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_artikel_veranstaltung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.artikel')),
                ('veranstaltung_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_autor_magazin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.autor')),
                ('magazin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.magazin')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_band_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_band_musiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band')),
                ('musiker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_buch_autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.autor')),
                ('buch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.buch')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_magazin_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
                ('magazin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.magazin')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_musiker_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
                ('musiker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_musiker_instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.instrument')),
                ('musiker_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.musiker')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_veranstaltung_band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.band')),
                ('veranstaltung_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_veranstaltung_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.genre')),
                ('veranstaltung_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung')),
            ],
        ),
        migrations.CreateModel(
            name='m2m_veranstaltung_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.person')),
                ('veranstaltung_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DBentry.veranstaltung')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='m2m_veranstaltung_person',
            unique_together=set([('veranstaltung_id', 'person_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_veranstaltung_genre',
            unique_together=set([('veranstaltung_id', 'genre_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_veranstaltung_band',
            unique_together=set([('veranstaltung_id', 'band_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_musiker_instrument',
            unique_together=set([('musiker_id', 'instrument_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_musiker_genre',
            unique_together=set([('musiker_id', 'genre_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_magazin_genre',
            unique_together=set([('magazin_id', 'genre_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_buch_autor',
            unique_together=set([('buch_id', 'autor_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_band_musiker',
            unique_together=set([('band_id', 'musiker_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_band_genre',
            unique_together=set([('band_id', 'genre_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_autor_magazin',
            unique_together=set([('autor_id', 'magazin_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_veranstaltung',
            unique_together=set([('artikel_id', 'veranstaltung_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_spielort',
            unique_together=set([('artikel_id', 'spielort_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_schlagwort',
            unique_together=set([('artikel_id', 'schlagwort_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_person',
            unique_together=set([('artikel_id', 'person_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_ort',
            unique_together=set([('artikel_id', 'ort_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_musiker',
            unique_together=set([('artikel_id', 'musiker_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_genre',
            unique_together=set([('artikel_id', 'genre_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_band',
            unique_together=set([('artikel_id', 'band_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='m2m_artikel_autor',
            unique_together=set([('artikel_id', 'autor_id')]),
        ),
    ]
