# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 12:27
from __future__ import unicode_literals

from django.db import migrations, models

def copy_m2m(apps, schema_editor):
    """ Copies all values of the auto-generated ManyToManyField model tables to an explicit table"""
    tbls = ['m2m_artikel_genre', 'm2m_band_genre', 'm2m_magazin_genre', 'm2m_musiker_genre', 'm2m_veranstaltung_genre', 
            'm2m_artikel_schlagwort', 'm2m_artikel_ort', 'm2m_artikel_spielort', 'm2m_artikel_veranstaltung', 
            'm2m_artikel_person', 'm2m_veranstaltung_person', 'm2m_artikel_autor', 'm2m_buch_autor', 'm2m_artikel_musiker', 
            'm2m_band_musiker', 'm2m_artikel_band', 'm2m_veranstaltung_band', 'm2m_musiker_instrument', 'm2m_autor_magazin']
    db_alias = schema_editor.connection.alias
    for tbl in tbls:
        target = apps.get_model('DBentry', tbl)
        source = apps.get_model('DBentry', tbl.replace("m2m_", ''))
        print("Copying {} to {}...".format(source._meta.model_name, target._meta.model_name))
        try:
            target.objects.using(db_alias).bulk_create([
                target(**values) for values in source.objects.using(db_alias).values()
            ])
            print("Done.\n\n")
        except Exception as e:
            raise e
        


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', '0051_DBentry_m2m_throughs'),
    ]

    operations = [
        migrations.RunPython(copy_m2m),
    ]
