# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBentry', 'DBentry_COPY_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='autor',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_autor', to='DBentry.autor'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='band',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_band', to='DBentry.band'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='musiker',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_musiker', to='DBentry.musiker'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='ort',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_ort', to='DBentry.ort'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='person',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_person', to='DBentry.person'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='schlagwort',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_schlagwort', to='DBentry.schlagwort'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='spielort',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_spielort', to='DBentry.spielort'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='veranstaltung',
            field=models.ManyToManyField(through='DBentry.m2m_artikel_veranstaltung', to='DBentry.veranstaltung'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='magazin',
            field=models.ManyToManyField(blank=True, through='DBentry.m2m_autor_magazin', to='DBentry.magazin'),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_band_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='band',
            name='musiker',
            field=models.ManyToManyField(through='DBentry.m2m_band_musiker', to='DBentry.musiker'),
        ),
        migrations.AlterField(
            model_name='buch',
            name='autor',
            field=models.ManyToManyField(through='DBentry.m2m_buch_autor', to='DBentry.autor'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='genre',
            field=models.ManyToManyField(blank=True, through='DBentry.m2m_magazin_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='musiker',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_musiker_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='musiker',
            name='instrument',
            field=models.ManyToManyField(through='DBentry.m2m_musiker_instrument', to='DBentry.instrument'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='band',
            field=models.ManyToManyField(through='DBentry.m2m_veranstaltung_band', to='DBentry.band', verbose_name='Teilnehmer (Bands)'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='genre',
            field=models.ManyToManyField(through='DBentry.m2m_veranstaltung_genre', to='DBentry.genre'),
        ),
        migrations.AlterField(
            model_name='veranstaltung',
            name='person',
            field=models.ManyToManyField(through='DBentry.m2m_veranstaltung_person', to='DBentry.person', verbose_name='Teilnehmer (Personen)'),
        ),
    ]
