"""
Django settings for MIZDB project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os  # noqa

# Add production variables:
try:
    from MIZDB.settings_prod import *  # noqa
except ImportError as e:
    raise ImportError("Production settings file 'MIZDB.settings_prod.py' missing.") from e

# Override production variables if DJANGO_DEVELOPMENT env variable is set.
# Credit to cs01: https://stackoverflow.com/a/34891731
if os.environ.get('DJANGO_DEVELOPMENT') == 'true':
    from MIZDB.settings_dev import *  # noqa